/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 47
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 30
#define ALIAS_COUNT 0
#define TOKEN_COUNT 16
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LF = 1,
  aux_sym_headline_token1 = 2,
  anon_sym_SPACE = 3,
  aux_sym_indent_token1 = 4,
  sym_main_line = 5,
  sym_other_line = 6,
  sym_open_checkbox = 7,
  sym_checked_checkbox = 8,
  sym_ongoing_checkbox = 9,
  sym_obsolete_checkbox = 10,
  sym_in_question_checkbox = 11,
  aux_sym_priority_token1 = 12,
  aux_sym_priority_token2 = 13,
  aux_sym_priority_token3 = 14,
  aux_sym_priority_token4 = 15,
  sym_document = 16,
  sym_headline = 17,
  sym_task = 18,
  sym_indent = 19,
  sym_open_task = 20,
  sym_checked_task = 21,
  sym_ongoing_task = 22,
  sym_obsolete_task = 23,
  sym_in_question_task = 24,
  sym_description = 25,
  sym_priority = 26,
  aux_sym_document_repeat1 = 27,
  aux_sym_empty_line_repeat1 = 28,
  aux_sym_description_repeat1 = 29,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [aux_sym_headline_token1] = "headline_token1",
  [anon_sym_SPACE] = " ",
  [aux_sym_indent_token1] = "indent_token1",
  [sym_main_line] = "main_line",
  [sym_other_line] = "other_line",
  [sym_open_checkbox] = "open_checkbox",
  [sym_checked_checkbox] = "checked_checkbox",
  [sym_ongoing_checkbox] = "ongoing_checkbox",
  [sym_obsolete_checkbox] = "obsolete_checkbox",
  [sym_in_question_checkbox] = "in_question_checkbox",
  [aux_sym_priority_token1] = "priority_token1",
  [aux_sym_priority_token2] = "priority_token2",
  [aux_sym_priority_token3] = "priority_token3",
  [aux_sym_priority_token4] = "priority_token4",
  [sym_document] = "document",
  [sym_headline] = "headline",
  [sym_task] = "task",
  [sym_indent] = "indent",
  [sym_open_task] = "open_task",
  [sym_checked_task] = "checked_task",
  [sym_ongoing_task] = "ongoing_task",
  [sym_obsolete_task] = "obsolete_task",
  [sym_in_question_task] = "in_question_task",
  [sym_description] = "description",
  [sym_priority] = "priority",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_empty_line_repeat1] = "empty_line_repeat1",
  [aux_sym_description_repeat1] = "description_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [aux_sym_headline_token1] = aux_sym_headline_token1,
  [anon_sym_SPACE] = anon_sym_SPACE,
  [aux_sym_indent_token1] = aux_sym_indent_token1,
  [sym_main_line] = sym_main_line,
  [sym_other_line] = sym_other_line,
  [sym_open_checkbox] = sym_open_checkbox,
  [sym_checked_checkbox] = sym_checked_checkbox,
  [sym_ongoing_checkbox] = sym_ongoing_checkbox,
  [sym_obsolete_checkbox] = sym_obsolete_checkbox,
  [sym_in_question_checkbox] = sym_in_question_checkbox,
  [aux_sym_priority_token1] = aux_sym_priority_token1,
  [aux_sym_priority_token2] = aux_sym_priority_token2,
  [aux_sym_priority_token3] = aux_sym_priority_token3,
  [aux_sym_priority_token4] = aux_sym_priority_token4,
  [sym_document] = sym_document,
  [sym_headline] = sym_headline,
  [sym_task] = sym_task,
  [sym_indent] = sym_indent,
  [sym_open_task] = sym_open_task,
  [sym_checked_task] = sym_checked_task,
  [sym_ongoing_task] = sym_ongoing_task,
  [sym_obsolete_task] = sym_obsolete_task,
  [sym_in_question_task] = sym_in_question_task,
  [sym_description] = sym_description,
  [sym_priority] = sym_priority,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_empty_line_repeat1] = aux_sym_empty_line_repeat1,
  [aux_sym_description_repeat1] = aux_sym_description_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_headline_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SPACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_indent_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_main_line] = {
    .visible = true,
    .named = true,
  },
  [sym_other_line] = {
    .visible = true,
    .named = true,
  },
  [sym_open_checkbox] = {
    .visible = true,
    .named = true,
  },
  [sym_checked_checkbox] = {
    .visible = true,
    .named = true,
  },
  [sym_ongoing_checkbox] = {
    .visible = true,
    .named = true,
  },
  [sym_obsolete_checkbox] = {
    .visible = true,
    .named = true,
  },
  [sym_in_question_checkbox] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_priority_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_priority_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_priority_token3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_priority_token4] = {
    .visible = false,
    .named = false,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_headline] = {
    .visible = true,
    .named = true,
  },
  [sym_task] = {
    .visible = true,
    .named = true,
  },
  [sym_indent] = {
    .visible = true,
    .named = true,
  },
  [sym_open_task] = {
    .visible = true,
    .named = true,
  },
  [sym_checked_task] = {
    .visible = true,
    .named = true,
  },
  [sym_ongoing_task] = {
    .visible = true,
    .named = true,
  },
  [sym_obsolete_task] = {
    .visible = true,
    .named = true,
  },
  [sym_in_question_task] = {
    .visible = true,
    .named = true,
  },
  [sym_description] = {
    .visible = true,
    .named = true,
  },
  [sym_priority] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_empty_line_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_description_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(17);
      if (lookahead == '\n') ADVANCE(18);
      if (lookahead == ' ') ADVANCE(20);
      if (lookahead == '!') ADVANCE(29);
      if (lookahead == '.') ADVANCE(6);
      if (lookahead == '[') ADVANCE(1);
      END_STATE();
    case 1:
      if (lookahead == ' ') ADVANCE(7);
      if (lookahead == '?') ADVANCE(8);
      if (lookahead == '@') ADVANCE(9);
      if (lookahead == 'x') ADVANCE(10);
      if (lookahead == '~') ADVANCE(11);
      END_STATE();
    case 2:
      if (lookahead == ' ') ADVANCE(21);
      END_STATE();
    case 3:
      if (lookahead == ' ') ADVANCE(2);
      END_STATE();
    case 4:
      if (lookahead == ' ') ADVANCE(3);
      END_STATE();
    case 5:
      if (lookahead == ' ') ADVANCE(4);
      END_STATE();
    case 6:
      if (lookahead == '!') ADVANCE(31);
      if (lookahead == '.') ADVANCE(32);
      END_STATE();
    case 7:
      if (lookahead == ']') ADVANCE(24);
      END_STATE();
    case 8:
      if (lookahead == ']') ADVANCE(28);
      END_STATE();
    case 9:
      if (lookahead == ']') ADVANCE(26);
      END_STATE();
    case 10:
      if (lookahead == ']') ADVANCE(25);
      END_STATE();
    case 11:
      if (lookahead == ']') ADVANCE(27);
      END_STATE();
    case 12:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 13:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(22);
      END_STATE();
    case 14:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(23);
      END_STATE();
    case 15:
      if (eof) ADVANCE(17);
      if (lookahead == '\n') ADVANCE(18);
      if (lookahead == ' ') ADVANCE(20);
      if (lookahead == '[') ADVANCE(1);
      if (lookahead != 0) ADVANCE(12);
      END_STATE();
    case 16:
      if (eof) ADVANCE(17);
      if (lookahead == '\n') ADVANCE(18);
      if (lookahead == '!') ADVANCE(29);
      if (lookahead == '.') ADVANCE(6);
      if (lookahead != 0) ADVANCE(13);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_headline_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_SPACE);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_indent_token1);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_main_line);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_other_line);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_open_checkbox);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_checked_checkbox);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_ongoing_checkbox);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_obsolete_checkbox);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_in_question_checkbox);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_priority_token1);
      if (lookahead == '!') ADVANCE(29);
      if (lookahead == '.') ADVANCE(30);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_priority_token2);
      if (lookahead == '.') ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_priority_token3);
      if (lookahead == '!') ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_priority_token4);
      if (lookahead == '!') ADVANCE(31);
      if (lookahead == '.') ADVANCE(32);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 15},
  [2] = {.lex_state = 15},
  [3] = {.lex_state = 15},
  [4] = {.lex_state = 15},
  [5] = {.lex_state = 16},
  [6] = {.lex_state = 16},
  [7] = {.lex_state = 16},
  [8] = {.lex_state = 15},
  [9] = {.lex_state = 16},
  [10] = {.lex_state = 16},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 5},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 5},
  [20] = {.lex_state = 5},
  [21] = {.lex_state = 5},
  [22] = {.lex_state = 5},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 16},
  [42] = {.lex_state = 14},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 5},
  [46] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [anon_sym_SPACE] = ACTIONS(1),
    [sym_open_checkbox] = ACTIONS(1),
    [sym_checked_checkbox] = ACTIONS(1),
    [sym_ongoing_checkbox] = ACTIONS(1),
    [sym_obsolete_checkbox] = ACTIONS(1),
    [sym_in_question_checkbox] = ACTIONS(1),
    [aux_sym_priority_token1] = ACTIONS(1),
    [aux_sym_priority_token2] = ACTIONS(1),
    [aux_sym_priority_token3] = ACTIONS(1),
    [aux_sym_priority_token4] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(44),
    [sym_headline] = STATE(2),
    [sym_task] = STATE(33),
    [sym_open_task] = STATE(27),
    [sym_checked_task] = STATE(27),
    [sym_ongoing_task] = STATE(27),
    [sym_obsolete_task] = STATE(27),
    [sym_in_question_task] = STATE(27),
    [aux_sym_document_repeat1] = STATE(2),
    [aux_sym_empty_line_repeat1] = STATE(15),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LF] = ACTIONS(5),
    [aux_sym_headline_token1] = ACTIONS(7),
    [anon_sym_SPACE] = ACTIONS(9),
    [sym_open_checkbox] = ACTIONS(11),
    [sym_checked_checkbox] = ACTIONS(13),
    [sym_ongoing_checkbox] = ACTIONS(15),
    [sym_obsolete_checkbox] = ACTIONS(17),
    [sym_in_question_checkbox] = ACTIONS(19),
  },
  [STATE(2)] = {
    [sym_headline] = STATE(3),
    [sym_task] = STATE(31),
    [sym_open_task] = STATE(27),
    [sym_checked_task] = STATE(27),
    [sym_ongoing_task] = STATE(27),
    [sym_obsolete_task] = STATE(27),
    [sym_in_question_task] = STATE(27),
    [aux_sym_document_repeat1] = STATE(3),
    [aux_sym_empty_line_repeat1] = STATE(15),
    [ts_builtin_sym_end] = ACTIONS(21),
    [anon_sym_LF] = ACTIONS(23),
    [aux_sym_headline_token1] = ACTIONS(7),
    [anon_sym_SPACE] = ACTIONS(9),
    [sym_open_checkbox] = ACTIONS(11),
    [sym_checked_checkbox] = ACTIONS(13),
    [sym_ongoing_checkbox] = ACTIONS(15),
    [sym_obsolete_checkbox] = ACTIONS(17),
    [sym_in_question_checkbox] = ACTIONS(19),
  },
  [STATE(3)] = {
    [sym_headline] = STATE(3),
    [sym_task] = STATE(39),
    [sym_open_task] = STATE(27),
    [sym_checked_task] = STATE(27),
    [sym_ongoing_task] = STATE(27),
    [sym_obsolete_task] = STATE(27),
    [sym_in_question_task] = STATE(27),
    [aux_sym_document_repeat1] = STATE(3),
    [aux_sym_empty_line_repeat1] = STATE(15),
    [ts_builtin_sym_end] = ACTIONS(25),
    [anon_sym_LF] = ACTIONS(27),
    [aux_sym_headline_token1] = ACTIONS(30),
    [anon_sym_SPACE] = ACTIONS(33),
    [sym_open_checkbox] = ACTIONS(36),
    [sym_checked_checkbox] = ACTIONS(39),
    [sym_ongoing_checkbox] = ACTIONS(42),
    [sym_obsolete_checkbox] = ACTIONS(45),
    [sym_in_question_checkbox] = ACTIONS(48),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 1,
    ACTIONS(51), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      aux_sym_headline_token1,
      anon_sym_SPACE,
      sym_open_checkbox,
      sym_checked_checkbox,
      sym_ongoing_checkbox,
      sym_obsolete_checkbox,
      sym_in_question_checkbox,
  [12] = 6,
    ACTIONS(55), 1,
      sym_main_line,
    STATE(25), 1,
      sym_description,
    STATE(38), 1,
      sym_priority,
    ACTIONS(53), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(57), 2,
      aux_sym_priority_token1,
      aux_sym_priority_token4,
    ACTIONS(59), 2,
      aux_sym_priority_token2,
      aux_sym_priority_token3,
  [34] = 6,
    ACTIONS(55), 1,
      sym_main_line,
    STATE(24), 1,
      sym_description,
    STATE(38), 1,
      sym_priority,
    ACTIONS(57), 2,
      aux_sym_priority_token1,
      aux_sym_priority_token4,
    ACTIONS(59), 2,
      aux_sym_priority_token2,
      aux_sym_priority_token3,
    ACTIONS(61), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [56] = 6,
    ACTIONS(55), 1,
      sym_main_line,
    STATE(28), 1,
      sym_description,
    STATE(38), 1,
      sym_priority,
    ACTIONS(57), 2,
      aux_sym_priority_token1,
      aux_sym_priority_token4,
    ACTIONS(59), 2,
      aux_sym_priority_token2,
      aux_sym_priority_token3,
    ACTIONS(63), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [78] = 1,
    ACTIONS(25), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      aux_sym_headline_token1,
      anon_sym_SPACE,
      sym_open_checkbox,
      sym_checked_checkbox,
      sym_ongoing_checkbox,
      sym_obsolete_checkbox,
      sym_in_question_checkbox,
  [90] = 6,
    ACTIONS(55), 1,
      sym_main_line,
    STATE(29), 1,
      sym_description,
    STATE(38), 1,
      sym_priority,
    ACTIONS(57), 2,
      aux_sym_priority_token1,
      aux_sym_priority_token4,
    ACTIONS(59), 2,
      aux_sym_priority_token2,
      aux_sym_priority_token3,
    ACTIONS(65), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [112] = 6,
    ACTIONS(55), 1,
      sym_main_line,
    STATE(26), 1,
      sym_description,
    STATE(38), 1,
      sym_priority,
    ACTIONS(57), 2,
      aux_sym_priority_token1,
      aux_sym_priority_token4,
    ACTIONS(59), 2,
      aux_sym_priority_token2,
      aux_sym_priority_token3,
    ACTIONS(67), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [134] = 2,
    ACTIONS(71), 1,
      anon_sym_SPACE,
    ACTIONS(69), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [142] = 2,
    ACTIONS(75), 1,
      anon_sym_SPACE,
    ACTIONS(73), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [150] = 2,
    ACTIONS(79), 1,
      anon_sym_SPACE,
    ACTIONS(77), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [158] = 2,
    ACTIONS(83), 1,
      anon_sym_SPACE,
    ACTIONS(81), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [166] = 3,
    ACTIONS(85), 1,
      anon_sym_LF,
    ACTIONS(87), 1,
      anon_sym_SPACE,
    STATE(18), 1,
      aux_sym_empty_line_repeat1,
  [176] = 2,
    ACTIONS(91), 1,
      anon_sym_SPACE,
    ACTIONS(89), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [184] = 3,
    ACTIONS(93), 1,
      aux_sym_indent_token1,
    STATE(19), 1,
      aux_sym_description_repeat1,
    STATE(23), 1,
      sym_indent,
  [194] = 3,
    ACTIONS(95), 1,
      anon_sym_LF,
    ACTIONS(97), 1,
      anon_sym_SPACE,
    STATE(18), 1,
      aux_sym_empty_line_repeat1,
  [204] = 3,
    ACTIONS(93), 1,
      aux_sym_indent_token1,
    STATE(20), 1,
      aux_sym_description_repeat1,
    STATE(34), 1,
      sym_indent,
  [214] = 3,
    ACTIONS(100), 1,
      aux_sym_indent_token1,
    STATE(20), 1,
      aux_sym_description_repeat1,
    STATE(46), 1,
      sym_indent,
  [224] = 3,
    ACTIONS(93), 1,
      aux_sym_indent_token1,
    STATE(22), 1,
      aux_sym_description_repeat1,
    STATE(35), 1,
      sym_indent,
  [234] = 3,
    ACTIONS(93), 1,
      aux_sym_indent_token1,
    STATE(20), 1,
      aux_sym_description_repeat1,
    STATE(37), 1,
      sym_indent,
  [244] = 2,
    ACTIONS(103), 1,
      ts_builtin_sym_end,
    ACTIONS(105), 1,
      anon_sym_LF,
  [251] = 1,
    ACTIONS(108), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [256] = 1,
    ACTIONS(110), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [261] = 1,
    ACTIONS(112), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [266] = 1,
    ACTIONS(114), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [271] = 1,
    ACTIONS(116), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [276] = 1,
    ACTIONS(118), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [281] = 1,
    ACTIONS(120), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [286] = 2,
    ACTIONS(85), 1,
      anon_sym_LF,
    ACTIONS(122), 1,
      ts_builtin_sym_end,
  [293] = 2,
    ACTIONS(103), 1,
      ts_builtin_sym_end,
    ACTIONS(124), 1,
      anon_sym_LF,
  [300] = 2,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(85), 1,
      anon_sym_LF,
  [307] = 2,
    ACTIONS(127), 1,
      ts_builtin_sym_end,
    ACTIONS(129), 1,
      anon_sym_LF,
  [314] = 2,
    ACTIONS(132), 1,
      ts_builtin_sym_end,
    ACTIONS(134), 1,
      anon_sym_LF,
  [321] = 2,
    ACTIONS(137), 1,
      ts_builtin_sym_end,
    ACTIONS(139), 1,
      anon_sym_LF,
  [328] = 2,
    ACTIONS(142), 1,
      ts_builtin_sym_end,
    ACTIONS(144), 1,
      anon_sym_LF,
  [335] = 1,
    ACTIONS(147), 1,
      anon_sym_SPACE,
  [339] = 1,
    ACTIONS(85), 1,
      anon_sym_LF,
  [343] = 1,
    ACTIONS(149), 1,
      anon_sym_SPACE,
  [347] = 1,
    ACTIONS(151), 1,
      sym_main_line,
  [351] = 1,
    ACTIONS(153), 1,
      sym_other_line,
  [355] = 1,
    ACTIONS(155), 1,
      anon_sym_LF,
  [359] = 1,
    ACTIONS(157), 1,
      ts_builtin_sym_end,
  [363] = 1,
    ACTIONS(159), 1,
      aux_sym_indent_token1,
  [367] = 1,
    ACTIONS(161), 1,
      anon_sym_LF,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 12,
  [SMALL_STATE(6)] = 34,
  [SMALL_STATE(7)] = 56,
  [SMALL_STATE(8)] = 78,
  [SMALL_STATE(9)] = 90,
  [SMALL_STATE(10)] = 112,
  [SMALL_STATE(11)] = 134,
  [SMALL_STATE(12)] = 142,
  [SMALL_STATE(13)] = 150,
  [SMALL_STATE(14)] = 158,
  [SMALL_STATE(15)] = 166,
  [SMALL_STATE(16)] = 176,
  [SMALL_STATE(17)] = 184,
  [SMALL_STATE(18)] = 194,
  [SMALL_STATE(19)] = 204,
  [SMALL_STATE(20)] = 214,
  [SMALL_STATE(21)] = 224,
  [SMALL_STATE(22)] = 234,
  [SMALL_STATE(23)] = 244,
  [SMALL_STATE(24)] = 251,
  [SMALL_STATE(25)] = 256,
  [SMALL_STATE(26)] = 261,
  [SMALL_STATE(27)] = 266,
  [SMALL_STATE(28)] = 271,
  [SMALL_STATE(29)] = 276,
  [SMALL_STATE(30)] = 281,
  [SMALL_STATE(31)] = 286,
  [SMALL_STATE(32)] = 293,
  [SMALL_STATE(33)] = 300,
  [SMALL_STATE(34)] = 307,
  [SMALL_STATE(35)] = 314,
  [SMALL_STATE(36)] = 321,
  [SMALL_STATE(37)] = 328,
  [SMALL_STATE(38)] = 335,
  [SMALL_STATE(39)] = 339,
  [SMALL_STATE(40)] = 343,
  [SMALL_STATE(41)] = 347,
  [SMALL_STATE(42)] = 351,
  [SMALL_STATE(43)] = 355,
  [SMALL_STATE(44)] = 359,
  [SMALL_STATE(45)] = 363,
  [SMALL_STATE(46)] = 367,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_headline, 2, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_open_task, 2, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_checked_task, 2, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ongoing_task, 2, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_in_question_task, 2, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_obsolete_task, 2, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ongoing_task, 1, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_open_task, 1, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_checked_task, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_in_question_task, 1, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_obsolete_task, 1, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_empty_line_repeat1, 2, 0, 0),
  [97] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_empty_line_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [100] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_description_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_description, 3, 0, 0),
  [105] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_description, 3, 0, 0), SHIFT(45),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_checked_task, 3, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_open_task, 3, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_obsolete_task, 3, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_task, 1, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ongoing_task, 3, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_in_question_task, 3, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_indent, 2, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 2, 0, 0),
  [124] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_description, 3, 0, 0), SHIFT(21),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_description, 4, 0, 0),
  [129] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_description, 4, 0, 0), SHIFT(45),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_description, 5, 0, 0),
  [134] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_description, 5, 0, 0), SHIFT(45),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_description, 1, 0, 0),
  [139] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_description, 1, 0, 0), SHIFT(17),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_description, 6, 0, 0),
  [144] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_description, 6, 0, 0), SHIFT(45),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_priority, 1, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [157] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_description_repeat1, 2, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_xit(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
