/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 61
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 52
#define ALIAS_COUNT 0
#define TOKEN_COUNT 23
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym__headers_token1 = 1,
  anon_sym_SPACE = 2,
  anon_sym_COMMA = 3,
  aux_sym_mailbox_sep_token1 = 4,
  sym_header_separator = 5,
  sym_header_field = 6,
  anon_sym_From = 7,
  anon_sym_To = 8,
  anon_sym_Cc = 9,
  anon_sym_Bcc = 10,
  anon_sym_Reply_DASHTo = 11,
  sym_header_field_subject = 12,
  aux_sym_header_unstructured_token1 = 13,
  sym_atom = 14,
  sym_quoted_string = 15,
  anon_sym_GT = 16,
  anon_sym_LT = 17,
  sym_email_address = 18,
  sym_body_signature_separator = 19,
  sym_quote_marker = 20,
  sym_quote_contents = 21,
  aux_sym__body_line_token1 = 22,
  sym_source_file = 23,
  aux_sym__headers = 24,
  sym__header = 25,
  sym_header_email = 26,
  sym_mailbox = 27,
  sym_mailbox_sep = 28,
  sym_header_other = 29,
  sym_header_subject = 30,
  sym_header_field_email = 31,
  sym_header_unstructured = 32,
  sym_subject = 33,
  sym_atom_block = 34,
  sym_email_delimiter = 35,
  sym_email = 36,
  sym_body_signature = 37,
  sym_body_separator = 38,
  sym_body = 39,
  sym_quote_group = 40,
  sym_quoted_block = 41,
  sym__quoted_line = 42,
  sym_body_block = 43,
  sym__body_line = 44,
  sym__empty_line = 45,
  aux_sym_header_email_repeat1 = 46,
  aux_sym_atom_block_repeat1 = 47,
  aux_sym_body_signature_repeat1 = 48,
  aux_sym_body_repeat1 = 49,
  aux_sym_quote_group_repeat1 = 50,
  aux_sym_body_block_repeat1 = 51,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym__headers_token1] = "_headers_token1",
  [anon_sym_SPACE] = " ",
  [anon_sym_COMMA] = ",",
  [aux_sym_mailbox_sep_token1] = "mailbox_sep_token1",
  [sym_header_separator] = "header_separator",
  [sym_header_field] = "header_field",
  [anon_sym_From] = "From",
  [anon_sym_To] = "To",
  [anon_sym_Cc] = "Cc",
  [anon_sym_Bcc] = "Bcc",
  [anon_sym_Reply_DASHTo] = "Reply-To",
  [sym_header_field_subject] = "header_field_subject",
  [aux_sym_header_unstructured_token1] = "header_unstructured_token1",
  [sym_atom] = "atom",
  [sym_quoted_string] = "quoted_string",
  [anon_sym_GT] = ">",
  [anon_sym_LT] = "<",
  [sym_email_address] = "email_address",
  [sym_body_signature_separator] = "body_signature_separator",
  [sym_quote_marker] = "quote_marker",
  [sym_quote_contents] = "quote_contents",
  [aux_sym__body_line_token1] = "_body_line_token1",
  [sym_source_file] = "source_file",
  [aux_sym__headers] = "_headers",
  [sym__header] = "_header",
  [sym_header_email] = "header_email",
  [sym_mailbox] = "mailbox",
  [sym_mailbox_sep] = "mailbox_sep",
  [sym_header_other] = "header_other",
  [sym_header_subject] = "header_subject",
  [sym_header_field_email] = "header_field_email",
  [sym_header_unstructured] = "header_unstructured",
  [sym_subject] = "subject",
  [sym_atom_block] = "atom_block",
  [sym_email_delimiter] = "email_delimiter",
  [sym_email] = "email",
  [sym_body_signature] = "body_signature",
  [sym_body_separator] = "body_separator",
  [sym_body] = "body",
  [sym_quote_group] = "quote_group",
  [sym_quoted_block] = "quoted_block",
  [sym__quoted_line] = "_quoted_line",
  [sym_body_block] = "body_block",
  [sym__body_line] = "_body_line",
  [sym__empty_line] = "_empty_line",
  [aux_sym_header_email_repeat1] = "header_email_repeat1",
  [aux_sym_atom_block_repeat1] = "atom_block_repeat1",
  [aux_sym_body_signature_repeat1] = "body_signature_repeat1",
  [aux_sym_body_repeat1] = "body_repeat1",
  [aux_sym_quote_group_repeat1] = "quote_group_repeat1",
  [aux_sym_body_block_repeat1] = "body_block_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym__headers_token1] = aux_sym__headers_token1,
  [anon_sym_SPACE] = anon_sym_SPACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [aux_sym_mailbox_sep_token1] = aux_sym_mailbox_sep_token1,
  [sym_header_separator] = sym_header_separator,
  [sym_header_field] = sym_header_field,
  [anon_sym_From] = anon_sym_From,
  [anon_sym_To] = anon_sym_To,
  [anon_sym_Cc] = anon_sym_Cc,
  [anon_sym_Bcc] = anon_sym_Bcc,
  [anon_sym_Reply_DASHTo] = anon_sym_Reply_DASHTo,
  [sym_header_field_subject] = sym_header_field_subject,
  [aux_sym_header_unstructured_token1] = aux_sym_header_unstructured_token1,
  [sym_atom] = sym_atom,
  [sym_quoted_string] = sym_quoted_string,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT] = anon_sym_LT,
  [sym_email_address] = sym_email_address,
  [sym_body_signature_separator] = sym_body_signature_separator,
  [sym_quote_marker] = sym_quote_marker,
  [sym_quote_contents] = sym_quote_contents,
  [aux_sym__body_line_token1] = aux_sym__body_line_token1,
  [sym_source_file] = sym_source_file,
  [aux_sym__headers] = aux_sym__headers,
  [sym__header] = sym__header,
  [sym_header_email] = sym_header_email,
  [sym_mailbox] = sym_mailbox,
  [sym_mailbox_sep] = sym_mailbox_sep,
  [sym_header_other] = sym_header_other,
  [sym_header_subject] = sym_header_subject,
  [sym_header_field_email] = sym_header_field_email,
  [sym_header_unstructured] = sym_header_unstructured,
  [sym_subject] = sym_subject,
  [sym_atom_block] = sym_atom_block,
  [sym_email_delimiter] = sym_email_delimiter,
  [sym_email] = sym_email,
  [sym_body_signature] = sym_body_signature,
  [sym_body_separator] = sym_body_separator,
  [sym_body] = sym_body,
  [sym_quote_group] = sym_quote_group,
  [sym_quoted_block] = sym_quoted_block,
  [sym__quoted_line] = sym__quoted_line,
  [sym_body_block] = sym_body_block,
  [sym__body_line] = sym__body_line,
  [sym__empty_line] = sym__empty_line,
  [aux_sym_header_email_repeat1] = aux_sym_header_email_repeat1,
  [aux_sym_atom_block_repeat1] = aux_sym_atom_block_repeat1,
  [aux_sym_body_signature_repeat1] = aux_sym_body_signature_repeat1,
  [aux_sym_body_repeat1] = aux_sym_body_repeat1,
  [aux_sym_quote_group_repeat1] = aux_sym_quote_group_repeat1,
  [aux_sym_body_block_repeat1] = aux_sym_body_block_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym__headers_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SPACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_mailbox_sep_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_header_separator] = {
    .visible = true,
    .named = true,
  },
  [sym_header_field] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_From] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_To] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Cc] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Bcc] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Reply_DASHTo] = {
    .visible = true,
    .named = false,
  },
  [sym_header_field_subject] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_header_unstructured_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_atom] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [sym_email_address] = {
    .visible = true,
    .named = true,
  },
  [sym_body_signature_separator] = {
    .visible = true,
    .named = true,
  },
  [sym_quote_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_quote_contents] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__body_line_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__headers] = {
    .visible = false,
    .named = false,
  },
  [sym__header] = {
    .visible = false,
    .named = true,
  },
  [sym_header_email] = {
    .visible = true,
    .named = true,
  },
  [sym_mailbox] = {
    .visible = true,
    .named = true,
  },
  [sym_mailbox_sep] = {
    .visible = true,
    .named = true,
  },
  [sym_header_other] = {
    .visible = true,
    .named = true,
  },
  [sym_header_subject] = {
    .visible = true,
    .named = true,
  },
  [sym_header_field_email] = {
    .visible = true,
    .named = true,
  },
  [sym_header_unstructured] = {
    .visible = true,
    .named = true,
  },
  [sym_subject] = {
    .visible = true,
    .named = true,
  },
  [sym_atom_block] = {
    .visible = true,
    .named = true,
  },
  [sym_email_delimiter] = {
    .visible = true,
    .named = true,
  },
  [sym_email] = {
    .visible = true,
    .named = true,
  },
  [sym_body_signature] = {
    .visible = true,
    .named = true,
  },
  [sym_body_separator] = {
    .visible = true,
    .named = true,
  },
  [sym_body] = {
    .visible = true,
    .named = true,
  },
  [sym_quote_group] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_block] = {
    .visible = true,
    .named = true,
  },
  [sym__quoted_line] = {
    .visible = false,
    .named = true,
  },
  [sym_body_block] = {
    .visible = true,
    .named = true,
  },
  [sym__body_line] = {
    .visible = false,
    .named = true,
  },
  [sym__empty_line] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_header_email_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_atom_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_body_signature_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quote_group_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_body_block_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 24,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 46,
  [60] = 60,
};

static const TSCharacterRange sym_atom_character_set_1[] = {
  {'!', '!'}, {'#', '\''}, {'*', '+'}, {'-', '-'}, {'/', '9'}, {'=', '='}, {'?', '?'}, {'A', 'Z'},
  {'^', '~'}, {0x80, 0x10ffff},
};

static const TSCharacterRange sym_email_address_character_set_1[] = {
  {'!', '!'}, {'#', '\''}, {'*', '+'}, {'-', '-'}, {'/', '9'}, {'=', '='}, {'?', '?'}, {'A', 'Z'},
  {'^', '~'},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(56);
      ADVANCE_MAP(
        '\t', 4,
        '\n', 58,
        '\r', 2,
        ' ', 61,
        '"', 9,
        ',', 65,
        ':', 67,
        '<', 131,
        '>', 130,
        'B', 112,
        'C', 109,
        'F', 122,
        'R', 113,
        'S', 124,
        'T', 118,
      );
      if (('!' <= lookahead && lookahead <= '\'') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('=' <= lookahead && lookahead <= '?') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('^' <= lookahead && lookahead <= '~')) ADVANCE(126);
      if (lookahead > 0x7f) ADVANCE(127);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '\t', 4,
        '\n', 58,
        '\r', 2,
        ' ', 61,
        '"', 9,
        ',', 65,
        '<', 131,
        '>', 130,
      );
      if (('!' <= lookahead && lookahead <= '\'') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('=' <= lookahead && lookahead <= '?') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('^' <= lookahead && lookahead <= '~')) ADVANCE(126);
      if (lookahead > 0x7f) ADVANCE(127);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(58);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(47);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(47);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '\n') ADVANCE(57);
      END_STATE();
    case 6:
      if (lookahead == '\n') ADVANCE(57);
      if (lookahead == '\r') ADVANCE(5);
      if (lookahead == ' ') ADVANCE(60);
      if (lookahead == '"') ADVANCE(9);
      if (lookahead == ',') ADVANCE(65);
      if (lookahead == '<') ADVANCE(131);
      if (lookahead == '>') ADVANCE(130);
      if (('!' <= lookahead && lookahead <= '\'') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('=' <= lookahead && lookahead <= '?') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('^' <= lookahead && lookahead <= '~')) ADVANCE(126);
      if (lookahead > 0x7f) ADVANCE(127);
      END_STATE();
    case 7:
      if (lookahead == '\n') ADVANCE(57);
      if (lookahead == '\r') ADVANCE(5);
      if (lookahead == ' ') ADVANCE(63);
      if (lookahead == '>') ADVANCE(137);
      if (lookahead != 0) ADVANCE(138);
      END_STATE();
    case 8:
      if (lookahead == '"') ADVANCE(42);
      if (lookahead == '\\') ADVANCE(52);
      if ((0x01 <= lookahead && lookahead <= 0x08) ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          (0x0e <= lookahead && lookahead <= 0x1f) ||
          ('!' <= lookahead && lookahead <= 0x7f)) ADVANCE(8);
      END_STATE();
    case 9:
      if (lookahead == '"') ADVANCE(42);
      if (lookahead == '\\') ADVANCE(52);
      if ((0x01 <= lookahead && lookahead <= 0x08) ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          (0x0e <= lookahead && lookahead <= 0x1f) ||
          ('!' <= lookahead && lookahead <= 0x7f)) ADVANCE(10);
      if (lookahead != 0 &&
          (lookahead < '\n' || '\f' < lookahead)) ADVANCE(11);
      END_STATE();
    case 10:
      if (lookahead == '"') ADVANCE(129);
      if (lookahead == '\\') ADVANCE(52);
      if ((0x01 <= lookahead && lookahead <= 0x08) ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          (0x0e <= lookahead && lookahead <= 0x1f) ||
          ('!' <= lookahead && lookahead <= 0x7f)) ADVANCE(10);
      if (lookahead != 0 &&
          (lookahead < '\n' || '\f' < lookahead)) ADVANCE(11);
      END_STATE();
    case 11:
      if (lookahead == '"') ADVANCE(128);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\\') ADVANCE(11);
      END_STATE();
    case 12:
      if (lookahead == '-') ADVANCE(13);
      if (lookahead == '.') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 13:
      if (lookahead == '-') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 14:
      if (lookahead == '-') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(133);
      END_STATE();
    case 15:
      if (lookahead == '-') ADVANCE(22);
      if (lookahead == '0') ADVANCE(20);
      if (lookahead == '1') ADVANCE(19);
      if (lookahead == '2') ADVANCE(16);
      if (('3' <= lookahead && lookahead <= '9')) ADVANCE(18);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 16:
      if (lookahead == '-') ADVANCE(22);
      if (lookahead == '5') ADVANCE(17);
      if (lookahead == ':') ADVANCE(46);
      if (lookahead == ']') ADVANCE(132);
      if (('6' <= lookahead && lookahead <= '9')) ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '4')) ADVANCE(18);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 17:
      if (lookahead == '-') ADVANCE(22);
      if (lookahead == ':') ADVANCE(46);
      if (lookahead == ']') ADVANCE(132);
      if (('0' <= lookahead && lookahead <= '5')) ADVANCE(20);
      if (('6' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 18:
      if (lookahead == '-') ADVANCE(22);
      if (lookahead == ':') ADVANCE(46);
      if (lookahead == ']') ADVANCE(132);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 19:
      if (lookahead == '-') ADVANCE(22);
      if (lookahead == ':') ADVANCE(46);
      if (lookahead == ']') ADVANCE(132);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 20:
      if (lookahead == '-') ADVANCE(22);
      if (lookahead == ':') ADVANCE(46);
      if (lookahead == ']') ADVANCE(132);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 21:
      if (lookahead == '-') ADVANCE(22);
      if (lookahead == ':') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 22:
      if (lookahead == '-') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 23:
      if (lookahead == '.') ADVANCE(51);
      if (lookahead == '@') ADVANCE(43);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '\'') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '9') ||
          lookahead == '=' ||
          ('?' <= lookahead && lookahead <= 'Z') ||
          ('^' <= lookahead && lookahead <= '~')) ADVANCE(23);
      END_STATE();
    case 24:
      if (lookahead == '.') ADVANCE(15);
      END_STATE();
    case 25:
      if (lookahead == '.') ADVANCE(15);
      if (lookahead == '5') ADVANCE(26);
      if (('6' <= lookahead && lookahead <= '9')) ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '4')) ADVANCE(27);
      END_STATE();
    case 26:
      if (lookahead == '.') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '5')) ADVANCE(24);
      END_STATE();
    case 27:
      if (lookahead == '.') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(24);
      END_STATE();
    case 28:
      if (lookahead == '.') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      END_STATE();
    case 29:
      if (lookahead == '.') ADVANCE(40);
      END_STATE();
    case 30:
      if (lookahead == '.') ADVANCE(40);
      if (lookahead == '5') ADVANCE(31);
      if (('6' <= lookahead && lookahead <= '9')) ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '4')) ADVANCE(32);
      END_STATE();
    case 31:
      if (lookahead == '.') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '5')) ADVANCE(29);
      END_STATE();
    case 32:
      if (lookahead == '.') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      END_STATE();
    case 33:
      if (lookahead == '.') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 34:
      if (lookahead == '.') ADVANCE(41);
      END_STATE();
    case 35:
      if (lookahead == '.') ADVANCE(41);
      if (lookahead == '5') ADVANCE(36);
      if (('6' <= lookahead && lookahead <= '9')) ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '4')) ADVANCE(37);
      END_STATE();
    case 36:
      if (lookahead == '.') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '5')) ADVANCE(34);
      END_STATE();
    case 37:
      if (lookahead == '.') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    case 38:
      if (lookahead == '.') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      END_STATE();
    case 39:
      if (lookahead == '0') ADVANCE(34);
      if (lookahead == '1') ADVANCE(38);
      if (lookahead == '2') ADVANCE(35);
      if (('3' <= lookahead && lookahead <= '9')) ADVANCE(37);
      END_STATE();
    case 40:
      if (lookahead == '0') ADVANCE(24);
      if (lookahead == '1') ADVANCE(28);
      if (lookahead == '2') ADVANCE(25);
      if (('3' <= lookahead && lookahead <= '9')) ADVANCE(27);
      END_STATE();
    case 41:
      if (lookahead == '0') ADVANCE(29);
      if (lookahead == '1') ADVANCE(33);
      if (lookahead == '2') ADVANCE(30);
      if (('3' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 42:
      if (lookahead == '@') ADVANCE(43);
      END_STATE();
    case 43:
      if (lookahead == '[') ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 44:
      if (lookahead == '\\') ADVANCE(45);
      if (lookahead == ']') ADVANCE(134);
      if ((0x01 <= lookahead && lookahead <= 0x08) ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          (0x0e <= lookahead && lookahead <= 0x1f) ||
          ('!' <= lookahead && lookahead <= 0x7f)) ADVANCE(44);
      END_STATE();
    case 45:
      if (lookahead == '\\') ADVANCE(45);
      if (lookahead == ']') ADVANCE(134);
      if ((0x01 <= lookahead && lookahead <= '\t') ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          (0x0e <= lookahead && lookahead <= 0x7f)) ADVANCE(44);
      END_STATE();
    case 46:
      if (lookahead == '\\') ADVANCE(45);
      if ((0x01 <= lookahead && lookahead <= 0x08) ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          (0x0e <= lookahead && lookahead <= 0x1f) ||
          ('!' <= lookahead && lookahead <= 0x7f)) ADVANCE(44);
      END_STATE();
    case 47:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(66);
      END_STATE();
    case 48:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(49);
      END_STATE();
    case 49:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(103);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(104);
      END_STATE();
    case 50:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(133);
      END_STATE();
    case 51:
      if (set_contains(sym_email_address_character_set_1, 9, lookahead)) ADVANCE(23);
      END_STATE();
    case 52:
      if ((0x01 <= lookahead && lookahead <= '\t') ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          (0x0e <= lookahead && lookahead <= 0x7f)) ADVANCE(8);
      END_STATE();
    case 53:
      if (eof) ADVANCE(56);
      ADVANCE_MAP(
        '\n', 57,
        '\r', 5,
        ' ', 60,
        ':', 67,
        'B', 74,
        'C', 71,
        'F', 84,
        'R', 75,
        'S', 86,
        'T', 80,
      );
      if (lookahead > ' ' &&
          lookahead != 0x7f) ADVANCE(88);
      END_STATE();
    case 54:
      if (eof) ADVANCE(56);
      if (lookahead == '\n') ADVANCE(57);
      if (lookahead == '\r') ADVANCE(5);
      if (lookahead == ' ') ADVANCE(64);
      if (lookahead == '-') ADVANCE(142);
      if (lookahead == '>') ADVANCE(137);
      if (lookahead != 0) ADVANCE(143);
      END_STATE();
    case 55:
      if (eof) ADVANCE(56);
      if (lookahead == '\n') ADVANCE(57);
      if (lookahead == '\r') ADVANCE(5);
      if (lookahead == ' ') ADVANCE(64);
      if (lookahead == '>') ADVANCE(137);
      if (lookahead != 0) ADVANCE(143);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym__headers_token1);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym__headers_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(66);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym__headers_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(49);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_SPACE);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_SPACE);
      if (lookahead == '\n') ADVANCE(47);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(4);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_SPACE);
      if (lookahead == '\n') ADVANCE(48);
      if (lookahead == '\r') ADVANCE(104);
      if (lookahead != 0) ADVANCE(104);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_SPACE);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(138);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_SPACE);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(143);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(aux_sym_mailbox_sep_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(66);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_header_separator);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_header_field);
      if (lookahead == '-') ADVANCE(69);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(88);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_header_field);
      if (lookahead == 'T') ADVANCE(82);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(88);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_header_field);
      if (lookahead == 'b') ADVANCE(77);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(88);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_header_field);
      if (lookahead == 'c') ADVANCE(94);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(88);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_header_field);
      if (lookahead == 'c') ADVANCE(96);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(88);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_header_field);
      if (lookahead == 'c') ADVANCE(85);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(88);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_header_field);
      if (lookahead == 'c') ADVANCE(72);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(88);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_header_field);
      if (lookahead == 'e') ADVANCE(83);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(88);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_header_field);
      if (lookahead == 'e') ADVANCE(73);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(88);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_header_field);
      if (lookahead == 'j') ADVANCE(76);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(88);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_header_field);
      if (lookahead == 'l') ADVANCE(87);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(88);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_header_field);
      if (lookahead == 'm') ADVANCE(90);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(88);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_header_field);
      if (lookahead == 'o') ADVANCE(92);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(88);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_header_field);
      if (lookahead == 'o') ADVANCE(79);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(88);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_header_field);
      if (lookahead == 'o') ADVANCE(98);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(88);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_header_field);
      if (lookahead == 'p') ADVANCE(78);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(88);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_header_field);
      if (lookahead == 'r') ADVANCE(81);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(88);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_header_field);
      if (lookahead == 't') ADVANCE(100);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(88);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_header_field);
      if (lookahead == 'u') ADVANCE(70);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(88);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_header_field);
      if (lookahead == 'y') ADVANCE(68);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(88);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_header_field);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(88);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_From);
      if (lookahead == '.') ADVANCE(51);
      if (lookahead == '@') ADVANCE(43);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '\'') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '9') ||
          lookahead == '=' ||
          ('?' <= lookahead && lookahead <= 'Z') ||
          ('^' <= lookahead && lookahead <= '~')) ADVANCE(126);
      if (lookahead > 0x7f) ADVANCE(127);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_From);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(88);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_To);
      if (lookahead == '.') ADVANCE(51);
      if (lookahead == '@') ADVANCE(43);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '\'') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '9') ||
          lookahead == '=' ||
          ('?' <= lookahead && lookahead <= 'Z') ||
          ('^' <= lookahead && lookahead <= '~')) ADVANCE(126);
      if (lookahead > 0x7f) ADVANCE(127);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_To);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(88);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_Cc);
      if (lookahead == '.') ADVANCE(51);
      if (lookahead == '@') ADVANCE(43);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '\'') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '9') ||
          lookahead == '=' ||
          ('?' <= lookahead && lookahead <= 'Z') ||
          ('^' <= lookahead && lookahead <= '~')) ADVANCE(126);
      if (lookahead > 0x7f) ADVANCE(127);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_Cc);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(88);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_Bcc);
      if (lookahead == '.') ADVANCE(51);
      if (lookahead == '@') ADVANCE(43);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '\'') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '9') ||
          lookahead == '=' ||
          ('?' <= lookahead && lookahead <= 'Z') ||
          ('^' <= lookahead && lookahead <= '~')) ADVANCE(126);
      if (lookahead > 0x7f) ADVANCE(127);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_Bcc);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(88);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_Reply_DASHTo);
      if (lookahead == '.') ADVANCE(51);
      if (lookahead == '@') ADVANCE(43);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '\'') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '9') ||
          lookahead == '=' ||
          ('?' <= lookahead && lookahead <= 'Z') ||
          ('^' <= lookahead && lookahead <= '~')) ADVANCE(126);
      if (lookahead > 0x7f) ADVANCE(127);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_Reply_DASHTo);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(88);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_header_field_subject);
      if (lookahead == '.') ADVANCE(51);
      if (lookahead == '@') ADVANCE(43);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '\'') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '9') ||
          lookahead == '=' ||
          ('?' <= lookahead && lookahead <= 'Z') ||
          ('^' <= lookahead && lookahead <= '~')) ADVANCE(126);
      if (lookahead > 0x7f) ADVANCE(127);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_header_field_subject);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(88);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(aux_sym_header_unstructured_token1);
      if (lookahead == '\n') ADVANCE(57);
      if (lookahead == '\r') ADVANCE(102);
      if (lookahead == ' ') ADVANCE(62);
      if (lookahead != 0) ADVANCE(104);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(aux_sym_header_unstructured_token1);
      if (lookahead == '\n') ADVANCE(59);
      if (lookahead == '\r') ADVANCE(104);
      if (lookahead != 0) ADVANCE(104);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(aux_sym_header_unstructured_token1);
      if (lookahead == '\n') ADVANCE(48);
      if (lookahead == '\r') ADVANCE(104);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(103);
      if (lookahead != 0) ADVANCE(104);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(aux_sym_header_unstructured_token1);
      if (lookahead == '\n') ADVANCE(48);
      if (lookahead == '\r') ADVANCE(104);
      if (lookahead != 0) ADVANCE(104);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(aux_sym_header_unstructured_token1);
      if (lookahead == ' ') ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(104);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == '-') ADVANCE(107);
      if (lookahead == '.') ADVANCE(51);
      if (lookahead == '@') ADVANCE(43);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '\'') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('/' <= lookahead && lookahead <= '9') ||
          lookahead == '=' ||
          ('?' <= lookahead && lookahead <= 'Z') ||
          ('^' <= lookahead && lookahead <= '~')) ADVANCE(126);
      if (lookahead > 0x7f) ADVANCE(127);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == '.') ADVANCE(51);
      if (lookahead == '@') ADVANCE(43);
      if (lookahead == 'T') ADVANCE(120);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '\'') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '9') ||
          lookahead == '=' ||
          ('?' <= lookahead && lookahead <= 'Z') ||
          ('^' <= lookahead && lookahead <= '~')) ADVANCE(126);
      if (lookahead > 0x7f) ADVANCE(127);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == '.') ADVANCE(51);
      if (lookahead == '@') ADVANCE(43);
      if (lookahead == 'b') ADVANCE(115);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '\'') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '9') ||
          lookahead == '=' ||
          ('?' <= lookahead && lookahead <= 'Z') ||
          ('^' <= lookahead && lookahead <= '~')) ADVANCE(126);
      if (lookahead > 0x7f) ADVANCE(127);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == '.') ADVANCE(51);
      if (lookahead == '@') ADVANCE(43);
      if (lookahead == 'c') ADVANCE(93);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '\'') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '9') ||
          lookahead == '=' ||
          ('?' <= lookahead && lookahead <= 'Z') ||
          ('^' <= lookahead && lookahead <= '~')) ADVANCE(126);
      if (lookahead > 0x7f) ADVANCE(127);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == '.') ADVANCE(51);
      if (lookahead == '@') ADVANCE(43);
      if (lookahead == 'c') ADVANCE(95);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '\'') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '9') ||
          lookahead == '=' ||
          ('?' <= lookahead && lookahead <= 'Z') ||
          ('^' <= lookahead && lookahead <= '~')) ADVANCE(126);
      if (lookahead > 0x7f) ADVANCE(127);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == '.') ADVANCE(51);
      if (lookahead == '@') ADVANCE(43);
      if (lookahead == 'c') ADVANCE(123);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '\'') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '9') ||
          lookahead == '=' ||
          ('?' <= lookahead && lookahead <= 'Z') ||
          ('^' <= lookahead && lookahead <= '~')) ADVANCE(126);
      if (lookahead > 0x7f) ADVANCE(127);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == '.') ADVANCE(51);
      if (lookahead == '@') ADVANCE(43);
      if (lookahead == 'c') ADVANCE(110);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '\'') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '9') ||
          lookahead == '=' ||
          ('?' <= lookahead && lookahead <= 'Z') ||
          ('^' <= lookahead && lookahead <= '~')) ADVANCE(126);
      if (lookahead > 0x7f) ADVANCE(127);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == '.') ADVANCE(51);
      if (lookahead == '@') ADVANCE(43);
      if (lookahead == 'e') ADVANCE(121);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '\'') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '9') ||
          lookahead == '=' ||
          ('?' <= lookahead && lookahead <= 'Z') ||
          ('^' <= lookahead && lookahead <= '~')) ADVANCE(126);
      if (lookahead > 0x7f) ADVANCE(127);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == '.') ADVANCE(51);
      if (lookahead == '@') ADVANCE(43);
      if (lookahead == 'e') ADVANCE(111);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '\'') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '9') ||
          lookahead == '=' ||
          ('?' <= lookahead && lookahead <= 'Z') ||
          ('^' <= lookahead && lookahead <= '~')) ADVANCE(126);
      if (lookahead > 0x7f) ADVANCE(127);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == '.') ADVANCE(51);
      if (lookahead == '@') ADVANCE(43);
      if (lookahead == 'j') ADVANCE(114);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '\'') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '9') ||
          lookahead == '=' ||
          ('?' <= lookahead && lookahead <= 'Z') ||
          ('^' <= lookahead && lookahead <= '~')) ADVANCE(126);
      if (lookahead > 0x7f) ADVANCE(127);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == '.') ADVANCE(51);
      if (lookahead == '@') ADVANCE(43);
      if (lookahead == 'l') ADVANCE(125);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '\'') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '9') ||
          lookahead == '=' ||
          ('?' <= lookahead && lookahead <= 'Z') ||
          ('^' <= lookahead && lookahead <= '~')) ADVANCE(126);
      if (lookahead > 0x7f) ADVANCE(127);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == '.') ADVANCE(51);
      if (lookahead == '@') ADVANCE(43);
      if (lookahead == 'm') ADVANCE(89);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '\'') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '9') ||
          lookahead == '=' ||
          ('?' <= lookahead && lookahead <= 'Z') ||
          ('^' <= lookahead && lookahead <= '~')) ADVANCE(126);
      if (lookahead > 0x7f) ADVANCE(127);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == '.') ADVANCE(51);
      if (lookahead == '@') ADVANCE(43);
      if (lookahead == 'o') ADVANCE(91);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '\'') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '9') ||
          lookahead == '=' ||
          ('?' <= lookahead && lookahead <= 'Z') ||
          ('^' <= lookahead && lookahead <= '~')) ADVANCE(126);
      if (lookahead > 0x7f) ADVANCE(127);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == '.') ADVANCE(51);
      if (lookahead == '@') ADVANCE(43);
      if (lookahead == 'o') ADVANCE(117);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '\'') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '9') ||
          lookahead == '=' ||
          ('?' <= lookahead && lookahead <= 'Z') ||
          ('^' <= lookahead && lookahead <= '~')) ADVANCE(126);
      if (lookahead > 0x7f) ADVANCE(127);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == '.') ADVANCE(51);
      if (lookahead == '@') ADVANCE(43);
      if (lookahead == 'o') ADVANCE(97);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '\'') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '9') ||
          lookahead == '=' ||
          ('?' <= lookahead && lookahead <= 'Z') ||
          ('^' <= lookahead && lookahead <= '~')) ADVANCE(126);
      if (lookahead > 0x7f) ADVANCE(127);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == '.') ADVANCE(51);
      if (lookahead == '@') ADVANCE(43);
      if (lookahead == 'p') ADVANCE(116);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '\'') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '9') ||
          lookahead == '=' ||
          ('?' <= lookahead && lookahead <= 'Z') ||
          ('^' <= lookahead && lookahead <= '~')) ADVANCE(126);
      if (lookahead > 0x7f) ADVANCE(127);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == '.') ADVANCE(51);
      if (lookahead == '@') ADVANCE(43);
      if (lookahead == 'r') ADVANCE(119);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '\'') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '9') ||
          lookahead == '=' ||
          ('?' <= lookahead && lookahead <= 'Z') ||
          ('^' <= lookahead && lookahead <= '~')) ADVANCE(126);
      if (lookahead > 0x7f) ADVANCE(127);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == '.') ADVANCE(51);
      if (lookahead == '@') ADVANCE(43);
      if (lookahead == 't') ADVANCE(99);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '\'') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '9') ||
          lookahead == '=' ||
          ('?' <= lookahead && lookahead <= 'Z') ||
          ('^' <= lookahead && lookahead <= '~')) ADVANCE(126);
      if (lookahead > 0x7f) ADVANCE(127);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == '.') ADVANCE(51);
      if (lookahead == '@') ADVANCE(43);
      if (lookahead == 'u') ADVANCE(108);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '\'') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '9') ||
          lookahead == '=' ||
          ('?' <= lookahead && lookahead <= 'Z') ||
          ('^' <= lookahead && lookahead <= '~')) ADVANCE(126);
      if (lookahead > 0x7f) ADVANCE(127);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == '.') ADVANCE(51);
      if (lookahead == '@') ADVANCE(43);
      if (lookahead == 'y') ADVANCE(106);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '\'') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '9') ||
          lookahead == '=' ||
          ('?' <= lookahead && lookahead <= 'Z') ||
          ('^' <= lookahead && lookahead <= '~')) ADVANCE(126);
      if (lookahead > 0x7f) ADVANCE(127);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == '.') ADVANCE(51);
      if (lookahead == '@') ADVANCE(43);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '\'') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '9') ||
          lookahead == '=' ||
          ('?' <= lookahead && lookahead <= 'Z') ||
          ('^' <= lookahead && lookahead <= '~')) ADVANCE(126);
      if (lookahead > 0x7f) ADVANCE(127);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(sym_atom);
      if (set_contains(sym_atom_character_set_1, 10, lookahead)) ADVANCE(127);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(sym_quoted_string);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(sym_quoted_string);
      if (lookahead == '@') ADVANCE(43);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(sym_email_address);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(sym_email_address);
      if (lookahead == '-') ADVANCE(14);
      if (lookahead == '.') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(133);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(sym_email_address);
      if (lookahead == '\\') ADVANCE(45);
      if (lookahead == ']') ADVANCE(134);
      if ((0x01 <= lookahead && lookahead <= 0x08) ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          (0x0e <= lookahead && lookahead <= 0x1f) ||
          ('!' <= lookahead && lookahead <= 0x7f)) ADVANCE(44);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(sym_body_signature_separator);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(sym_quote_marker);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(sym_quote_marker);
      if (lookahead == ' ') ADVANCE(136);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(sym_quote_contents);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(138);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(aux_sym__body_line_token1);
      if (lookahead == '\n') ADVANCE(135);
      if (lookahead == '\r') ADVANCE(140);
      if (lookahead != 0) ADVANCE(143);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(aux_sym__body_line_token1);
      if (lookahead == '\n') ADVANCE(135);
      if (lookahead != 0) ADVANCE(143);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(aux_sym__body_line_token1);
      if (lookahead == ' ') ADVANCE(139);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(143);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(aux_sym__body_line_token1);
      if (lookahead == '-') ADVANCE(141);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(143);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(aux_sym__body_line_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(143);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 53},
  [2] = {.lex_state = 53},
  [3] = {.lex_state = 53},
  [4] = {.lex_state = 54},
  [5] = {.lex_state = 54},
  [6] = {.lex_state = 55},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 53},
  [10] = {.lex_state = 54},
  [11] = {.lex_state = 54},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 54},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 54},
  [17] = {.lex_state = 55},
  [18] = {.lex_state = 6},
  [19] = {.lex_state = 55},
  [20] = {.lex_state = 6},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 55},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 54},
  [25] = {.lex_state = 54},
  [26] = {.lex_state = 6},
  [27] = {.lex_state = 6},
  [28] = {.lex_state = 7},
  [29] = {.lex_state = 6},
  [30] = {.lex_state = 55},
  [31] = {.lex_state = 101},
  [32] = {.lex_state = 6},
  [33] = {.lex_state = 6},
  [34] = {.lex_state = 55},
  [35] = {.lex_state = 6},
  [36] = {.lex_state = 6},
  [37] = {.lex_state = 6},
  [38] = {.lex_state = 105},
  [39] = {.lex_state = 6},
  [40] = {.lex_state = 6},
  [41] = {.lex_state = 53},
  [42] = {.lex_state = 53},
  [43] = {.lex_state = 53},
  [44] = {.lex_state = 53},
  [45] = {.lex_state = 53},
  [46] = {.lex_state = 53},
  [47] = {.lex_state = 53},
  [48] = {.lex_state = 53},
  [49] = {.lex_state = 53},
  [50] = {.lex_state = 53},
  [51] = {.lex_state = 53},
  [52] = {.lex_state = 53},
  [53] = {.lex_state = 53},
  [54] = {.lex_state = 6},
  [55] = {.lex_state = 53},
  [56] = {.lex_state = 53},
  [57] = {.lex_state = 53},
  [58] = {.lex_state = 53},
  [59] = {.lex_state = 53},
  [60] = {.lex_state = 53},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym__headers_token1] = ACTIONS(1),
    [anon_sym_SPACE] = ACTIONS(3),
    [anon_sym_COMMA] = ACTIONS(1),
    [aux_sym_mailbox_sep_token1] = ACTIONS(1),
    [sym_header_separator] = ACTIONS(1),
    [anon_sym_From] = ACTIONS(1),
    [anon_sym_To] = ACTIONS(1),
    [anon_sym_Cc] = ACTIONS(1),
    [anon_sym_Bcc] = ACTIONS(1),
    [anon_sym_Reply_DASHTo] = ACTIONS(1),
    [sym_header_field_subject] = ACTIONS(1),
    [sym_atom] = ACTIONS(1),
    [sym_quoted_string] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [sym_email_address] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(43),
    [aux_sym__headers] = STATE(2),
    [sym__header] = STATE(52),
    [sym_header_email] = STATE(52),
    [sym_header_other] = STATE(52),
    [sym_header_subject] = STATE(52),
    [sym_header_field_email] = STATE(53),
    [anon_sym_SPACE] = ACTIONS(5),
    [sym_header_field] = ACTIONS(7),
    [anon_sym_From] = ACTIONS(9),
    [anon_sym_To] = ACTIONS(9),
    [anon_sym_Cc] = ACTIONS(9),
    [anon_sym_Bcc] = ACTIONS(9),
    [anon_sym_Reply_DASHTo] = ACTIONS(9),
    [sym_header_field_subject] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(5), 1,
      anon_sym_SPACE,
    ACTIONS(7), 1,
      sym_header_field,
    ACTIONS(11), 1,
      sym_header_field_subject,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    ACTIONS(15), 1,
      aux_sym__headers_token1,
    STATE(3), 1,
      aux_sym__headers,
    STATE(6), 1,
      sym_body_separator,
    STATE(53), 1,
      sym_header_field_email,
    STATE(52), 4,
      sym__header,
      sym_header_email,
      sym_header_other,
      sym_header_subject,
    ACTIONS(9), 5,
      anon_sym_From,
      anon_sym_To,
      anon_sym_Cc,
      anon_sym_Bcc,
      anon_sym_Reply_DASHTo,
  [38] = 8,
    ACTIONS(5), 1,
      anon_sym_SPACE,
    ACTIONS(19), 1,
      sym_header_field,
    ACTIONS(25), 1,
      sym_header_field_subject,
    STATE(3), 1,
      aux_sym__headers,
    STATE(53), 1,
      sym_header_field_email,
    ACTIONS(17), 2,
      ts_builtin_sym_end,
      aux_sym__headers_token1,
    STATE(52), 4,
      sym__header,
      sym_header_email,
      sym_header_other,
      sym_header_subject,
    ACTIONS(22), 5,
      anon_sym_From,
      anon_sym_To,
      anon_sym_Cc,
      anon_sym_Bcc,
      anon_sym_Reply_DASHTo,
  [71] = 9,
    ACTIONS(3), 1,
      anon_sym_SPACE,
    ACTIONS(30), 1,
      aux_sym__headers_token1,
    ACTIONS(33), 1,
      sym_quote_marker,
    ACTIONS(36), 1,
      aux_sym__body_line_token1,
    STATE(48), 1,
      sym_quoted_block,
    ACTIONS(28), 2,
      ts_builtin_sym_end,
      sym_body_signature_separator,
    STATE(10), 2,
      sym__quoted_line,
      aux_sym_quote_group_repeat1,
    STATE(14), 2,
      sym__body_line,
      aux_sym_body_block_repeat1,
    STATE(4), 4,
      sym_quote_group,
      sym_body_block,
      sym__empty_line,
      aux_sym_body_repeat1,
  [105] = 10,
    ACTIONS(3), 1,
      anon_sym_SPACE,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
    ACTIONS(41), 1,
      aux_sym__headers_token1,
    ACTIONS(43), 1,
      sym_body_signature_separator,
    ACTIONS(45), 1,
      sym_quote_marker,
    ACTIONS(47), 1,
      aux_sym__body_line_token1,
    STATE(48), 1,
      sym_quoted_block,
    STATE(10), 2,
      sym__quoted_line,
      aux_sym_quote_group_repeat1,
    STATE(14), 2,
      sym__body_line,
      aux_sym_body_block_repeat1,
    STATE(4), 4,
      sym_quote_group,
      sym_body_block,
      sym__empty_line,
      aux_sym_body_repeat1,
  [141] = 9,
    ACTIONS(3), 1,
      anon_sym_SPACE,
    ACTIONS(45), 1,
      sym_quote_marker,
    ACTIONS(47), 1,
      aux_sym__body_line_token1,
    ACTIONS(49), 1,
      aux_sym__headers_token1,
    STATE(47), 1,
      sym_body,
    STATE(48), 1,
      sym_quoted_block,
    STATE(10), 2,
      sym__quoted_line,
      aux_sym_quote_group_repeat1,
    STATE(14), 2,
      sym__body_line,
      aux_sym_body_block_repeat1,
    STATE(5), 4,
      sym_quote_group,
      sym_body_block,
      sym__empty_line,
      aux_sym_body_repeat1,
  [174] = 11,
    ACTIONS(3), 1,
      anon_sym_SPACE,
    ACTIONS(51), 1,
      aux_sym__headers_token1,
    ACTIONS(53), 1,
      aux_sym_mailbox_sep_token1,
    ACTIONS(59), 1,
      sym_email_address,
    STATE(13), 1,
      aux_sym_atom_block_repeat1,
    STATE(18), 1,
      sym_atom_block,
    STATE(29), 1,
      sym_mailbox,
    STATE(35), 1,
      sym_email,
    STATE(54), 1,
      sym_email_delimiter,
    ACTIONS(55), 2,
      sym_atom,
      sym_quoted_string,
    ACTIONS(57), 2,
      anon_sym_GT,
      anon_sym_LT,
  [210] = 10,
    ACTIONS(3), 1,
      anon_sym_SPACE,
    ACTIONS(53), 1,
      aux_sym_mailbox_sep_token1,
    ACTIONS(59), 1,
      sym_email_address,
    STATE(13), 1,
      aux_sym_atom_block_repeat1,
    STATE(18), 1,
      sym_atom_block,
    STATE(35), 1,
      sym_email,
    STATE(39), 1,
      sym_mailbox,
    STATE(54), 1,
      sym_email_delimiter,
    ACTIONS(55), 2,
      sym_atom,
      sym_quoted_string,
    ACTIONS(57), 2,
      anon_sym_GT,
      anon_sym_LT,
  [243] = 3,
    ACTIONS(5), 1,
      anon_sym_SPACE,
    ACTIONS(17), 2,
      ts_builtin_sym_end,
      aux_sym__headers_token1,
    ACTIONS(61), 7,
      sym_header_field,
      anon_sym_From,
      anon_sym_To,
      anon_sym_Cc,
      anon_sym_Bcc,
      anon_sym_Reply_DASHTo,
      sym_header_field_subject,
  [260] = 6,
    ACTIONS(3), 1,
      anon_sym_SPACE,
    ACTIONS(45), 1,
      sym_quote_marker,
    ACTIONS(65), 1,
      aux_sym__body_line_token1,
    STATE(48), 1,
      sym_quoted_block,
    STATE(11), 2,
      sym__quoted_line,
      aux_sym_quote_group_repeat1,
    ACTIONS(63), 3,
      ts_builtin_sym_end,
      aux_sym__headers_token1,
      sym_body_signature_separator,
  [282] = 6,
    ACTIONS(3), 1,
      anon_sym_SPACE,
    ACTIONS(69), 1,
      sym_quote_marker,
    ACTIONS(72), 1,
      aux_sym__body_line_token1,
    STATE(48), 1,
      sym_quoted_block,
    STATE(11), 2,
      sym__quoted_line,
      aux_sym_quote_group_repeat1,
    ACTIONS(67), 3,
      ts_builtin_sym_end,
      aux_sym__headers_token1,
      sym_body_signature_separator,
  [304] = 6,
    ACTIONS(3), 1,
      anon_sym_SPACE,
    ACTIONS(74), 1,
      aux_sym__headers_token1,
    ACTIONS(78), 1,
      aux_sym_mailbox_sep_token1,
    STATE(12), 1,
      aux_sym_atom_block_repeat1,
    ACTIONS(81), 2,
      sym_atom,
      sym_quoted_string,
    ACTIONS(76), 3,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_LT,
  [326] = 6,
    ACTIONS(3), 1,
      anon_sym_SPACE,
    ACTIONS(84), 1,
      aux_sym__headers_token1,
    ACTIONS(88), 1,
      aux_sym_mailbox_sep_token1,
    STATE(12), 1,
      aux_sym_atom_block_repeat1,
    ACTIONS(90), 2,
      sym_atom,
      sym_quoted_string,
    ACTIONS(86), 3,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_LT,
  [348] = 4,
    ACTIONS(3), 1,
      anon_sym_SPACE,
    ACTIONS(47), 1,
      aux_sym__body_line_token1,
    STATE(16), 2,
      sym__body_line,
      aux_sym_body_block_repeat1,
    ACTIONS(92), 4,
      ts_builtin_sym_end,
      aux_sym__headers_token1,
      sym_body_signature_separator,
      sym_quote_marker,
  [365] = 3,
    ACTIONS(3), 1,
      anon_sym_SPACE,
    ACTIONS(74), 1,
      aux_sym__headers_token1,
    ACTIONS(76), 6,
      anon_sym_COMMA,
      aux_sym_mailbox_sep_token1,
      sym_atom,
      sym_quoted_string,
      anon_sym_GT,
      anon_sym_LT,
  [380] = 4,
    ACTIONS(3), 1,
      anon_sym_SPACE,
    ACTIONS(96), 1,
      aux_sym__body_line_token1,
    STATE(16), 2,
      sym__body_line,
      aux_sym_body_block_repeat1,
    ACTIONS(94), 4,
      ts_builtin_sym_end,
      aux_sym__headers_token1,
      sym_body_signature_separator,
      sym_quote_marker,
  [397] = 5,
    ACTIONS(3), 1,
      anon_sym_SPACE,
    ACTIONS(99), 1,
      aux_sym__headers_token1,
    ACTIONS(101), 1,
      aux_sym__body_line_token1,
    STATE(44), 1,
      sym_body_signature,
    STATE(19), 3,
      sym__body_line,
      sym__empty_line,
      aux_sym_body_signature_repeat1,
  [415] = 5,
    ACTIONS(5), 1,
      anon_sym_SPACE,
    STATE(37), 1,
      sym_email,
    STATE(54), 1,
      sym_email_delimiter,
    ACTIONS(57), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(103), 2,
      aux_sym__headers_token1,
      anon_sym_COMMA,
  [433] = 5,
    ACTIONS(3), 1,
      anon_sym_SPACE,
    ACTIONS(101), 1,
      aux_sym__body_line_token1,
    ACTIONS(105), 1,
      ts_builtin_sym_end,
    ACTIONS(107), 1,
      aux_sym__headers_token1,
    STATE(22), 3,
      sym__body_line,
      sym__empty_line,
      aux_sym_body_signature_repeat1,
  [451] = 3,
    ACTIONS(5), 1,
      anon_sym_SPACE,
    ACTIONS(111), 2,
      sym_atom,
      sym_quoted_string,
    ACTIONS(109), 4,
      aux_sym__headers_token1,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_LT,
  [465] = 4,
    ACTIONS(3), 1,
      anon_sym_SPACE,
    ACTIONS(113), 1,
      aux_sym_mailbox_sep_token1,
    ACTIONS(115), 2,
      sym_atom,
      sym_quoted_string,
    ACTIONS(117), 3,
      anon_sym_GT,
      anon_sym_LT,
      sym_email_address,
  [481] = 5,
    ACTIONS(3), 1,
      anon_sym_SPACE,
    ACTIONS(119), 1,
      ts_builtin_sym_end,
    ACTIONS(121), 1,
      aux_sym__headers_token1,
    ACTIONS(124), 1,
      aux_sym__body_line_token1,
    STATE(22), 3,
      sym__body_line,
      sym__empty_line,
      aux_sym_body_signature_repeat1,
  [499] = 3,
    ACTIONS(3), 1,
      anon_sym_SPACE,
    ACTIONS(129), 2,
      sym_atom,
      sym_quoted_string,
    ACTIONS(127), 4,
      aux_sym_mailbox_sep_token1,
      anon_sym_GT,
      anon_sym_LT,
      sym_email_address,
  [513] = 3,
    ACTIONS(3), 1,
      anon_sym_SPACE,
    ACTIONS(133), 1,
      aux_sym__body_line_token1,
    ACTIONS(131), 4,
      ts_builtin_sym_end,
      aux_sym__headers_token1,
      sym_body_signature_separator,
      sym_quote_marker,
  [526] = 3,
    ACTIONS(3), 1,
      anon_sym_SPACE,
    ACTIONS(137), 1,
      aux_sym__body_line_token1,
    ACTIONS(135), 4,
      ts_builtin_sym_end,
      aux_sym__headers_token1,
      sym_body_signature_separator,
      sym_quote_marker,
  [539] = 5,
    ACTIONS(5), 1,
      anon_sym_SPACE,
    ACTIONS(139), 1,
      aux_sym__headers_token1,
    ACTIONS(141), 1,
      anon_sym_COMMA,
    STATE(8), 1,
      sym_mailbox_sep,
    STATE(27), 1,
      aux_sym_header_email_repeat1,
  [555] = 5,
    ACTIONS(5), 1,
      anon_sym_SPACE,
    ACTIONS(143), 1,
      aux_sym__headers_token1,
    ACTIONS(145), 1,
      anon_sym_COMMA,
    STATE(8), 1,
      sym_mailbox_sep,
    STATE(27), 1,
      aux_sym_header_email_repeat1,
  [571] = 5,
    ACTIONS(3), 1,
      anon_sym_SPACE,
    ACTIONS(45), 1,
      sym_quote_marker,
    ACTIONS(148), 1,
      aux_sym__headers_token1,
    ACTIONS(150), 1,
      sym_quote_contents,
    STATE(50), 1,
      sym_quoted_block,
  [587] = 5,
    ACTIONS(5), 1,
      anon_sym_SPACE,
    ACTIONS(141), 1,
      anon_sym_COMMA,
    ACTIONS(152), 1,
      aux_sym__headers_token1,
    STATE(8), 1,
      sym_mailbox_sep,
    STATE(26), 1,
      aux_sym_header_email_repeat1,
  [603] = 3,
    ACTIONS(3), 1,
      anon_sym_SPACE,
    ACTIONS(156), 1,
      aux_sym__body_line_token1,
    ACTIONS(154), 2,
      aux_sym__headers_token1,
      sym_quote_marker,
  [614] = 4,
    ACTIONS(3), 1,
      anon_sym_SPACE,
    ACTIONS(158), 1,
      aux_sym__headers_token1,
    ACTIONS(160), 1,
      aux_sym_header_unstructured_token1,
    STATE(55), 1,
      sym_header_unstructured,
  [627] = 2,
    ACTIONS(5), 1,
      anon_sym_SPACE,
    ACTIONS(162), 3,
      aux_sym__headers_token1,
      anon_sym_COMMA,
      sym_email_address,
  [636] = 3,
    ACTIONS(5), 1,
      anon_sym_SPACE,
    STATE(40), 1,
      sym_email_delimiter,
    ACTIONS(57), 2,
      anon_sym_GT,
      anon_sym_LT,
  [647] = 3,
    ACTIONS(3), 1,
      anon_sym_SPACE,
    ACTIONS(133), 1,
      aux_sym__body_line_token1,
    ACTIONS(131), 2,
      ts_builtin_sym_end,
      aux_sym__headers_token1,
  [658] = 2,
    ACTIONS(5), 1,
      anon_sym_SPACE,
    ACTIONS(103), 2,
      aux_sym__headers_token1,
      anon_sym_COMMA,
  [666] = 2,
    ACTIONS(5), 1,
      anon_sym_SPACE,
    ACTIONS(111), 2,
      sym_atom,
      sym_quoted_string,
  [674] = 2,
    ACTIONS(5), 1,
      anon_sym_SPACE,
    ACTIONS(164), 2,
      aux_sym__headers_token1,
      anon_sym_COMMA,
  [682] = 3,
    ACTIONS(3), 1,
      anon_sym_SPACE,
    ACTIONS(166), 1,
      aux_sym_header_unstructured_token1,
    STATE(56), 1,
      sym_subject,
  [692] = 2,
    ACTIONS(5), 1,
      anon_sym_SPACE,
    ACTIONS(143), 2,
      aux_sym__headers_token1,
      anon_sym_COMMA,
  [700] = 2,
    ACTIONS(5), 1,
      anon_sym_SPACE,
    ACTIONS(168), 2,
      aux_sym__headers_token1,
      anon_sym_COMMA,
  [708] = 2,
    ACTIONS(5), 1,
      anon_sym_SPACE,
    ACTIONS(170), 1,
      aux_sym__headers_token1,
  [715] = 2,
    ACTIONS(5), 1,
      anon_sym_SPACE,
    ACTIONS(172), 1,
      aux_sym__headers_token1,
  [722] = 2,
    ACTIONS(5), 1,
      anon_sym_SPACE,
    ACTIONS(174), 1,
      ts_builtin_sym_end,
  [729] = 2,
    ACTIONS(5), 1,
      anon_sym_SPACE,
    ACTIONS(176), 1,
      ts_builtin_sym_end,
  [736] = 2,
    ACTIONS(178), 1,
      aux_sym__headers_token1,
    ACTIONS(180), 1,
      anon_sym_SPACE,
  [743] = 2,
    ACTIONS(5), 1,
      anon_sym_SPACE,
    ACTIONS(182), 1,
      aux_sym__headers_token1,
  [750] = 2,
    ACTIONS(5), 1,
      anon_sym_SPACE,
    ACTIONS(184), 1,
      ts_builtin_sym_end,
  [757] = 2,
    ACTIONS(5), 1,
      anon_sym_SPACE,
    ACTIONS(186), 1,
      aux_sym__headers_token1,
  [764] = 2,
    ACTIONS(5), 1,
      anon_sym_SPACE,
    ACTIONS(188), 1,
      sym_header_separator,
  [771] = 2,
    ACTIONS(5), 1,
      anon_sym_SPACE,
    ACTIONS(190), 1,
      aux_sym__headers_token1,
  [778] = 2,
    ACTIONS(192), 1,
      aux_sym__headers_token1,
    ACTIONS(194), 1,
      anon_sym_SPACE,
  [785] = 2,
    ACTIONS(5), 1,
      anon_sym_SPACE,
    ACTIONS(196), 1,
      aux_sym__headers_token1,
  [792] = 2,
    ACTIONS(5), 1,
      anon_sym_SPACE,
    ACTIONS(198), 1,
      sym_header_separator,
  [799] = 2,
    ACTIONS(5), 1,
      anon_sym_SPACE,
    ACTIONS(200), 1,
      sym_email_address,
  [806] = 2,
    ACTIONS(5), 1,
      anon_sym_SPACE,
    ACTIONS(202), 1,
      aux_sym__headers_token1,
  [813] = 2,
    ACTIONS(5), 1,
      anon_sym_SPACE,
    ACTIONS(204), 1,
      aux_sym__headers_token1,
  [820] = 2,
    ACTIONS(5), 1,
      anon_sym_SPACE,
    ACTIONS(206), 1,
      sym_header_separator,
  [827] = 2,
    ACTIONS(5), 1,
      anon_sym_SPACE,
    ACTIONS(208), 1,
      sym_header_separator,
  [834] = 2,
    ACTIONS(5), 1,
      anon_sym_SPACE,
    ACTIONS(210), 1,
      aux_sym__headers_token1,
  [841] = 1,
    ACTIONS(212), 1,
      anon_sym_SPACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 38,
  [SMALL_STATE(4)] = 71,
  [SMALL_STATE(5)] = 105,
  [SMALL_STATE(6)] = 141,
  [SMALL_STATE(7)] = 174,
  [SMALL_STATE(8)] = 210,
  [SMALL_STATE(9)] = 243,
  [SMALL_STATE(10)] = 260,
  [SMALL_STATE(11)] = 282,
  [SMALL_STATE(12)] = 304,
  [SMALL_STATE(13)] = 326,
  [SMALL_STATE(14)] = 348,
  [SMALL_STATE(15)] = 365,
  [SMALL_STATE(16)] = 380,
  [SMALL_STATE(17)] = 397,
  [SMALL_STATE(18)] = 415,
  [SMALL_STATE(19)] = 433,
  [SMALL_STATE(20)] = 451,
  [SMALL_STATE(21)] = 465,
  [SMALL_STATE(22)] = 481,
  [SMALL_STATE(23)] = 499,
  [SMALL_STATE(24)] = 513,
  [SMALL_STATE(25)] = 526,
  [SMALL_STATE(26)] = 539,
  [SMALL_STATE(27)] = 555,
  [SMALL_STATE(28)] = 571,
  [SMALL_STATE(29)] = 587,
  [SMALL_STATE(30)] = 603,
  [SMALL_STATE(31)] = 614,
  [SMALL_STATE(32)] = 627,
  [SMALL_STATE(33)] = 636,
  [SMALL_STATE(34)] = 647,
  [SMALL_STATE(35)] = 658,
  [SMALL_STATE(36)] = 666,
  [SMALL_STATE(37)] = 674,
  [SMALL_STATE(38)] = 682,
  [SMALL_STATE(39)] = 692,
  [SMALL_STATE(40)] = 700,
  [SMALL_STATE(41)] = 708,
  [SMALL_STATE(42)] = 715,
  [SMALL_STATE(43)] = 722,
  [SMALL_STATE(44)] = 729,
  [SMALL_STATE(45)] = 736,
  [SMALL_STATE(46)] = 743,
  [SMALL_STATE(47)] = 750,
  [SMALL_STATE(48)] = 757,
  [SMALL_STATE(49)] = 764,
  [SMALL_STATE(50)] = 771,
  [SMALL_STATE(51)] = 778,
  [SMALL_STATE(52)] = 785,
  [SMALL_STATE(53)] = 792,
  [SMALL_STATE(54)] = 799,
  [SMALL_STATE(55)] = 806,
  [SMALL_STATE(56)] = 813,
  [SMALL_STATE(57)] = 820,
  [SMALL_STATE(58)] = 827,
  [SMALL_STATE(59)] = 834,
  [SMALL_STATE(60)] = 841,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__headers, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__headers, 2, 0, 0), SHIFT_REPEAT(49),
  [22] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__headers, 2, 0, 0), SHIFT_REPEAT(57),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__headers, 2, 0, 0), SHIFT_REPEAT(58),
  [28] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 1, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_header_email, 3, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__headers, 2, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote_group, 1, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quote_group, 1, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_quote_group_repeat1, 2, 0, 0),
  [69] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote_group_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quote_group_repeat1, 2, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_atom_block_repeat1, 2, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_atom_block_repeat1, 2, 0, 0),
  [78] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_atom_block_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [81] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_atom_block_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_atom_block, 1, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_atom_block, 1, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body_block, 1, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_body_block_repeat1, 2, 0, 0),
  [96] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_block_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [101] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mailbox, 1, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body_signature, 1, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_atom_block, 2, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_mailbox_sep, 1, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mailbox_sep, 1, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_body_signature_repeat1, 2, 0, 0),
  [121] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_signature_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [124] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_signature_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mailbox_sep, 2, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_mailbox_sep, 2, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__body_line, 2, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__body_line, 2, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__quoted_line, 2, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__quoted_line, 2, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header_email, 5, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_header_email_repeat1, 2, 0, 0),
  [145] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_header_email_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_block, 1, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header_email, 4, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body_separator, 1, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_body_separator, 1, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_header_other, 3, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_email_delimiter, 1, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mailbox, 2, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_email, 3, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header_unstructured, 1, 0, 0),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 1, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 3, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header_email, 2, 0, 0),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_block, 2, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header_other, 2, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header_other, 4, 0, 0),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header_subject, 4, 0, 0),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header_field_email, 1, 0, 0),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_mail(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "mail",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
