/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 25
#define LARGE_STATE_COUNT 9
#define SYMBOL_COUNT 40
#define ALIAS_COUNT 0
#define TOKEN_COUNT 30
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_PERCENT = 1,
  aux_sym_width_token1 = 2,
  anon_sym_DOT = 3,
  anon_sym_a = 4,
  anon_sym_A = 5,
  anon_sym_b = 6,
  anon_sym_B = 7,
  anon_sym_c = 8,
  anon_sym_d = 9,
  anon_sym_e = 10,
  anon_sym_E = 11,
  anon_sym_f = 12,
  anon_sym_g = 13,
  anon_sym_G = 14,
  anon_sym_i = 15,
  anon_sym_o = 16,
  anon_sym_u = 17,
  anon_sym_p = 18,
  anon_sym_q = 19,
  anon_sym_s = 20,
  anon_sym_x = 21,
  anon_sym_X = 22,
  sym_escaped_percent_sign = 23,
  anon_sym_PLUS = 24,
  anon_sym_DASH = 25,
  anon_sym_POUND = 26,
  anon_sym_SPACE = 27,
  anon_sym_0 = 28,
  sym_text = 29,
  sym_format_string = 30,
  sym__maybe_format = 31,
  sym_directive = 32,
  sym_width = 33,
  sym_precision = 34,
  sym__width_and_precision = 35,
  sym_conversion_specifier = 36,
  sym_flag = 37,
  aux_sym_format_string_repeat1 = 38,
  aux_sym_directive_repeat1 = 39,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_PERCENT] = "%",
  [aux_sym_width_token1] = "width_token1",
  [anon_sym_DOT] = ".",
  [anon_sym_a] = "a",
  [anon_sym_A] = "A",
  [anon_sym_b] = "b",
  [anon_sym_B] = "B",
  [anon_sym_c] = "c",
  [anon_sym_d] = "d",
  [anon_sym_e] = "e",
  [anon_sym_E] = "E",
  [anon_sym_f] = "f",
  [anon_sym_g] = "g",
  [anon_sym_G] = "G",
  [anon_sym_i] = "i",
  [anon_sym_o] = "o",
  [anon_sym_u] = "u",
  [anon_sym_p] = "p",
  [anon_sym_q] = "q",
  [anon_sym_s] = "s",
  [anon_sym_x] = "x",
  [anon_sym_X] = "X",
  [sym_escaped_percent_sign] = "escaped_percent_sign",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_POUND] = "#",
  [anon_sym_SPACE] = " ",
  [anon_sym_0] = "0",
  [sym_text] = "text",
  [sym_format_string] = "format_string",
  [sym__maybe_format] = "_maybe_format",
  [sym_directive] = "directive",
  [sym_width] = "width",
  [sym_precision] = "precision",
  [sym__width_and_precision] = "_width_and_precision",
  [sym_conversion_specifier] = "conversion_specifier",
  [sym_flag] = "flag",
  [aux_sym_format_string_repeat1] = "format_string_repeat1",
  [aux_sym_directive_repeat1] = "directive_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [aux_sym_width_token1] = aux_sym_width_token1,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_a] = anon_sym_a,
  [anon_sym_A] = anon_sym_A,
  [anon_sym_b] = anon_sym_b,
  [anon_sym_B] = anon_sym_B,
  [anon_sym_c] = anon_sym_c,
  [anon_sym_d] = anon_sym_d,
  [anon_sym_e] = anon_sym_e,
  [anon_sym_E] = anon_sym_E,
  [anon_sym_f] = anon_sym_f,
  [anon_sym_g] = anon_sym_g,
  [anon_sym_G] = anon_sym_G,
  [anon_sym_i] = anon_sym_i,
  [anon_sym_o] = anon_sym_o,
  [anon_sym_u] = anon_sym_u,
  [anon_sym_p] = anon_sym_p,
  [anon_sym_q] = anon_sym_q,
  [anon_sym_s] = anon_sym_s,
  [anon_sym_x] = anon_sym_x,
  [anon_sym_X] = anon_sym_X,
  [sym_escaped_percent_sign] = sym_escaped_percent_sign,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_SPACE] = anon_sym_SPACE,
  [anon_sym_0] = anon_sym_0,
  [sym_text] = sym_text,
  [sym_format_string] = sym_format_string,
  [sym__maybe_format] = sym__maybe_format,
  [sym_directive] = sym_directive,
  [sym_width] = sym_width,
  [sym_precision] = sym_precision,
  [sym__width_and_precision] = sym__width_and_precision,
  [sym_conversion_specifier] = sym_conversion_specifier,
  [sym_flag] = sym_flag,
  [aux_sym_format_string_repeat1] = aux_sym_format_string_repeat1,
  [aux_sym_directive_repeat1] = aux_sym_directive_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_width_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_a] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_A] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_b] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_B] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_c] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_d] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_e] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_E] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_f] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_g] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_G] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_i] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_o] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_p] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_q] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_s] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_x] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_X] = {
    .visible = true,
    .named = false,
  },
  [sym_escaped_percent_sign] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SPACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_0] = {
    .visible = true,
    .named = false,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_format_string] = {
    .visible = true,
    .named = true,
  },
  [sym__maybe_format] = {
    .visible = false,
    .named = true,
  },
  [sym_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_width] = {
    .visible = true,
    .named = true,
  },
  [sym_precision] = {
    .visible = true,
    .named = true,
  },
  [sym__width_and_precision] = {
    .visible = false,
    .named = true,
  },
  [sym_conversion_specifier] = {
    .visible = true,
    .named = true,
  },
  [sym_flag] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_format_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_directive_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(2);
      ADVANCE_MAP(
        ' ', 30,
        '#', 29,
        '%', 3,
        '+', 27,
        '-', 28,
        '.', 6,
        '0', 31,
        'A', 8,
        'B', 10,
        'E', 14,
        'G', 17,
        'X', 25,
        'a', 7,
        'b', 9,
        'c', 11,
        'd', 12,
        'e', 13,
        'f', 15,
        'g', 16,
        'i', 18,
        'o', 19,
        'p', 21,
        'q', 22,
        's', 23,
        'u', 20,
        'x', 24,
      );
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(5);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '.', 6,
        '0', 4,
        'A', 8,
        'B', 10,
        'E', 14,
        'G', 17,
        'X', 25,
        'a', 7,
        'b', 9,
        'c', 11,
        'd', 12,
        'e', 13,
        'f', 15,
        'g', 16,
        'i', 18,
        'o', 19,
        'p', 21,
        'q', 22,
        's', 23,
        'u', 20,
        'x', 24,
      );
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(5);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      if (lookahead == '%') ADVANCE(26);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(aux_sym_width_token1);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(aux_sym_width_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(4);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_a);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_A);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_b);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_B);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_c);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_d);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_e);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_E);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_f);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_g);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_G);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_i);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_o);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_u);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_p);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_q);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_s);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_x);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_X);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_escaped_percent_sign);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_SPACE);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_0);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '%') ADVANCE(32);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 32},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 32},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 32},
  [22] = {.lex_state = 32},
  [23] = {.lex_state = 32},
  [24] = {.lex_state = 32},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [aux_sym_width_token1] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_a] = ACTIONS(1),
    [anon_sym_A] = ACTIONS(1),
    [anon_sym_b] = ACTIONS(1),
    [anon_sym_B] = ACTIONS(1),
    [anon_sym_c] = ACTIONS(1),
    [anon_sym_d] = ACTIONS(1),
    [anon_sym_e] = ACTIONS(1),
    [anon_sym_E] = ACTIONS(1),
    [anon_sym_f] = ACTIONS(1),
    [anon_sym_g] = ACTIONS(1),
    [anon_sym_G] = ACTIONS(1),
    [anon_sym_i] = ACTIONS(1),
    [anon_sym_o] = ACTIONS(1),
    [anon_sym_u] = ACTIONS(1),
    [anon_sym_p] = ACTIONS(1),
    [anon_sym_q] = ACTIONS(1),
    [anon_sym_s] = ACTIONS(1),
    [anon_sym_x] = ACTIONS(1),
    [anon_sym_X] = ACTIONS(1),
    [sym_escaped_percent_sign] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_SPACE] = ACTIONS(1),
    [anon_sym_0] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_format_string] = STATE(20),
    [sym_text] = ACTIONS(3),
  },
  [STATE(2)] = {
    [sym_width] = STATE(6),
    [sym__width_and_precision] = STATE(9),
    [sym_conversion_specifier] = STATE(22),
    [sym_flag] = STATE(3),
    [aux_sym_directive_repeat1] = STATE(3),
    [aux_sym_width_token1] = ACTIONS(5),
    [anon_sym_DOT] = ACTIONS(7),
    [anon_sym_a] = ACTIONS(9),
    [anon_sym_A] = ACTIONS(9),
    [anon_sym_b] = ACTIONS(9),
    [anon_sym_B] = ACTIONS(9),
    [anon_sym_c] = ACTIONS(9),
    [anon_sym_d] = ACTIONS(9),
    [anon_sym_e] = ACTIONS(9),
    [anon_sym_E] = ACTIONS(9),
    [anon_sym_f] = ACTIONS(9),
    [anon_sym_g] = ACTIONS(9),
    [anon_sym_G] = ACTIONS(9),
    [anon_sym_i] = ACTIONS(9),
    [anon_sym_o] = ACTIONS(9),
    [anon_sym_u] = ACTIONS(9),
    [anon_sym_p] = ACTIONS(9),
    [anon_sym_q] = ACTIONS(9),
    [anon_sym_s] = ACTIONS(9),
    [anon_sym_x] = ACTIONS(9),
    [anon_sym_X] = ACTIONS(9),
    [anon_sym_PLUS] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_POUND] = ACTIONS(11),
    [anon_sym_SPACE] = ACTIONS(11),
    [anon_sym_0] = ACTIONS(11),
  },
  [STATE(3)] = {
    [sym_width] = STATE(6),
    [sym__width_and_precision] = STATE(10),
    [sym_conversion_specifier] = STATE(23),
    [sym_flag] = STATE(4),
    [aux_sym_directive_repeat1] = STATE(4),
    [aux_sym_width_token1] = ACTIONS(5),
    [anon_sym_DOT] = ACTIONS(7),
    [anon_sym_a] = ACTIONS(9),
    [anon_sym_A] = ACTIONS(9),
    [anon_sym_b] = ACTIONS(9),
    [anon_sym_B] = ACTIONS(9),
    [anon_sym_c] = ACTIONS(9),
    [anon_sym_d] = ACTIONS(9),
    [anon_sym_e] = ACTIONS(9),
    [anon_sym_E] = ACTIONS(9),
    [anon_sym_f] = ACTIONS(9),
    [anon_sym_g] = ACTIONS(9),
    [anon_sym_G] = ACTIONS(9),
    [anon_sym_i] = ACTIONS(9),
    [anon_sym_o] = ACTIONS(9),
    [anon_sym_u] = ACTIONS(9),
    [anon_sym_p] = ACTIONS(9),
    [anon_sym_q] = ACTIONS(9),
    [anon_sym_s] = ACTIONS(9),
    [anon_sym_x] = ACTIONS(9),
    [anon_sym_X] = ACTIONS(9),
    [anon_sym_PLUS] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_POUND] = ACTIONS(11),
    [anon_sym_SPACE] = ACTIONS(11),
    [anon_sym_0] = ACTIONS(11),
  },
  [STATE(4)] = {
    [sym_flag] = STATE(4),
    [aux_sym_directive_repeat1] = STATE(4),
    [aux_sym_width_token1] = ACTIONS(13),
    [anon_sym_DOT] = ACTIONS(15),
    [anon_sym_a] = ACTIONS(15),
    [anon_sym_A] = ACTIONS(15),
    [anon_sym_b] = ACTIONS(15),
    [anon_sym_B] = ACTIONS(15),
    [anon_sym_c] = ACTIONS(15),
    [anon_sym_d] = ACTIONS(15),
    [anon_sym_e] = ACTIONS(15),
    [anon_sym_E] = ACTIONS(15),
    [anon_sym_f] = ACTIONS(15),
    [anon_sym_g] = ACTIONS(15),
    [anon_sym_G] = ACTIONS(15),
    [anon_sym_i] = ACTIONS(15),
    [anon_sym_o] = ACTIONS(15),
    [anon_sym_u] = ACTIONS(15),
    [anon_sym_p] = ACTIONS(15),
    [anon_sym_q] = ACTIONS(15),
    [anon_sym_s] = ACTIONS(15),
    [anon_sym_x] = ACTIONS(15),
    [anon_sym_X] = ACTIONS(15),
    [anon_sym_PLUS] = ACTIONS(17),
    [anon_sym_DASH] = ACTIONS(17),
    [anon_sym_POUND] = ACTIONS(17),
    [anon_sym_SPACE] = ACTIONS(17),
    [anon_sym_0] = ACTIONS(17),
  },
  [STATE(5)] = {
    [aux_sym_width_token1] = ACTIONS(20),
    [anon_sym_DOT] = ACTIONS(22),
    [anon_sym_a] = ACTIONS(22),
    [anon_sym_A] = ACTIONS(22),
    [anon_sym_b] = ACTIONS(22),
    [anon_sym_B] = ACTIONS(22),
    [anon_sym_c] = ACTIONS(22),
    [anon_sym_d] = ACTIONS(22),
    [anon_sym_e] = ACTIONS(22),
    [anon_sym_E] = ACTIONS(22),
    [anon_sym_f] = ACTIONS(22),
    [anon_sym_g] = ACTIONS(22),
    [anon_sym_G] = ACTIONS(22),
    [anon_sym_i] = ACTIONS(22),
    [anon_sym_o] = ACTIONS(22),
    [anon_sym_u] = ACTIONS(22),
    [anon_sym_p] = ACTIONS(22),
    [anon_sym_q] = ACTIONS(22),
    [anon_sym_s] = ACTIONS(22),
    [anon_sym_x] = ACTIONS(22),
    [anon_sym_X] = ACTIONS(22),
    [anon_sym_PLUS] = ACTIONS(22),
    [anon_sym_DASH] = ACTIONS(22),
    [anon_sym_POUND] = ACTIONS(22),
    [anon_sym_SPACE] = ACTIONS(22),
    [anon_sym_0] = ACTIONS(22),
  },
  [STATE(6)] = {
    [sym_precision] = STATE(12),
    [aux_sym_width_token1] = ACTIONS(24),
    [anon_sym_DOT] = ACTIONS(26),
    [anon_sym_a] = ACTIONS(28),
    [anon_sym_A] = ACTIONS(28),
    [anon_sym_b] = ACTIONS(28),
    [anon_sym_B] = ACTIONS(28),
    [anon_sym_c] = ACTIONS(28),
    [anon_sym_d] = ACTIONS(28),
    [anon_sym_e] = ACTIONS(28),
    [anon_sym_E] = ACTIONS(28),
    [anon_sym_f] = ACTIONS(28),
    [anon_sym_g] = ACTIONS(28),
    [anon_sym_G] = ACTIONS(28),
    [anon_sym_i] = ACTIONS(28),
    [anon_sym_o] = ACTIONS(28),
    [anon_sym_u] = ACTIONS(28),
    [anon_sym_p] = ACTIONS(28),
    [anon_sym_q] = ACTIONS(28),
    [anon_sym_s] = ACTIONS(28),
    [anon_sym_x] = ACTIONS(28),
    [anon_sym_X] = ACTIONS(28),
  },
  [STATE(7)] = {
    [aux_sym_width_token1] = ACTIONS(30),
    [anon_sym_DOT] = ACTIONS(30),
    [anon_sym_a] = ACTIONS(30),
    [anon_sym_A] = ACTIONS(30),
    [anon_sym_b] = ACTIONS(30),
    [anon_sym_B] = ACTIONS(30),
    [anon_sym_c] = ACTIONS(30),
    [anon_sym_d] = ACTIONS(30),
    [anon_sym_e] = ACTIONS(30),
    [anon_sym_E] = ACTIONS(30),
    [anon_sym_f] = ACTIONS(30),
    [anon_sym_g] = ACTIONS(30),
    [anon_sym_G] = ACTIONS(30),
    [anon_sym_i] = ACTIONS(30),
    [anon_sym_o] = ACTIONS(30),
    [anon_sym_u] = ACTIONS(30),
    [anon_sym_p] = ACTIONS(30),
    [anon_sym_q] = ACTIONS(30),
    [anon_sym_s] = ACTIONS(30),
    [anon_sym_x] = ACTIONS(30),
    [anon_sym_X] = ACTIONS(30),
  },
  [STATE(8)] = {
    [sym_precision] = STATE(13),
    [aux_sym_width_token1] = ACTIONS(24),
    [anon_sym_a] = ACTIONS(32),
    [anon_sym_A] = ACTIONS(32),
    [anon_sym_b] = ACTIONS(32),
    [anon_sym_B] = ACTIONS(32),
    [anon_sym_c] = ACTIONS(32),
    [anon_sym_d] = ACTIONS(32),
    [anon_sym_e] = ACTIONS(32),
    [anon_sym_E] = ACTIONS(32),
    [anon_sym_f] = ACTIONS(32),
    [anon_sym_g] = ACTIONS(32),
    [anon_sym_G] = ACTIONS(32),
    [anon_sym_i] = ACTIONS(32),
    [anon_sym_o] = ACTIONS(32),
    [anon_sym_u] = ACTIONS(32),
    [anon_sym_p] = ACTIONS(32),
    [anon_sym_q] = ACTIONS(32),
    [anon_sym_s] = ACTIONS(32),
    [anon_sym_x] = ACTIONS(32),
    [anon_sym_X] = ACTIONS(32),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    STATE(23), 1,
      sym_conversion_specifier,
    ACTIONS(9), 19,
      anon_sym_a,
      anon_sym_A,
      anon_sym_b,
      anon_sym_B,
      anon_sym_c,
      anon_sym_d,
      anon_sym_e,
      anon_sym_E,
      anon_sym_f,
      anon_sym_g,
      anon_sym_G,
      anon_sym_i,
      anon_sym_o,
      anon_sym_u,
      anon_sym_p,
      anon_sym_q,
      anon_sym_s,
      anon_sym_x,
      anon_sym_X,
  [25] = 2,
    STATE(24), 1,
      sym_conversion_specifier,
    ACTIONS(9), 19,
      anon_sym_a,
      anon_sym_A,
      anon_sym_b,
      anon_sym_B,
      anon_sym_c,
      anon_sym_d,
      anon_sym_e,
      anon_sym_E,
      anon_sym_f,
      anon_sym_g,
      anon_sym_G,
      anon_sym_i,
      anon_sym_o,
      anon_sym_u,
      anon_sym_p,
      anon_sym_q,
      anon_sym_s,
      anon_sym_x,
      anon_sym_X,
  [50] = 1,
    ACTIONS(34), 19,
      anon_sym_a,
      anon_sym_A,
      anon_sym_b,
      anon_sym_B,
      anon_sym_c,
      anon_sym_d,
      anon_sym_e,
      anon_sym_E,
      anon_sym_f,
      anon_sym_g,
      anon_sym_G,
      anon_sym_i,
      anon_sym_o,
      anon_sym_u,
      anon_sym_p,
      anon_sym_q,
      anon_sym_s,
      anon_sym_x,
      anon_sym_X,
  [72] = 1,
    ACTIONS(32), 19,
      anon_sym_a,
      anon_sym_A,
      anon_sym_b,
      anon_sym_B,
      anon_sym_c,
      anon_sym_d,
      anon_sym_e,
      anon_sym_E,
      anon_sym_f,
      anon_sym_g,
      anon_sym_G,
      anon_sym_i,
      anon_sym_o,
      anon_sym_u,
      anon_sym_p,
      anon_sym_q,
      anon_sym_s,
      anon_sym_x,
      anon_sym_X,
  [94] = 1,
    ACTIONS(36), 19,
      anon_sym_a,
      anon_sym_A,
      anon_sym_b,
      anon_sym_B,
      anon_sym_c,
      anon_sym_d,
      anon_sym_e,
      anon_sym_E,
      anon_sym_f,
      anon_sym_g,
      anon_sym_G,
      anon_sym_i,
      anon_sym_o,
      anon_sym_u,
      anon_sym_p,
      anon_sym_q,
      anon_sym_s,
      anon_sym_x,
      anon_sym_X,
  [116] = 5,
    ACTIONS(38), 1,
      ts_builtin_sym_end,
    ACTIONS(40), 1,
      anon_sym_PERCENT,
    ACTIONS(42), 1,
      sym_escaped_percent_sign,
    STATE(15), 1,
      aux_sym_format_string_repeat1,
    STATE(19), 2,
      sym__maybe_format,
      sym_directive,
  [133] = 5,
    ACTIONS(40), 1,
      anon_sym_PERCENT,
    ACTIONS(42), 1,
      sym_escaped_percent_sign,
    ACTIONS(44), 1,
      ts_builtin_sym_end,
    STATE(16), 1,
      aux_sym_format_string_repeat1,
    STATE(19), 2,
      sym__maybe_format,
      sym_directive,
  [150] = 5,
    ACTIONS(46), 1,
      ts_builtin_sym_end,
    ACTIONS(48), 1,
      anon_sym_PERCENT,
    ACTIONS(51), 1,
      sym_escaped_percent_sign,
    STATE(16), 1,
      aux_sym_format_string_repeat1,
    STATE(19), 2,
      sym__maybe_format,
      sym_directive,
  [167] = 2,
    ACTIONS(54), 1,
      anon_sym_PERCENT,
    ACTIONS(46), 2,
      ts_builtin_sym_end,
      sym_escaped_percent_sign,
  [175] = 2,
    ACTIONS(24), 1,
      aux_sym_width_token1,
    STATE(12), 1,
      sym_precision,
  [182] = 1,
    ACTIONS(56), 1,
      sym_text,
  [186] = 1,
    ACTIONS(58), 1,
      ts_builtin_sym_end,
  [190] = 1,
    ACTIONS(60), 1,
      sym_text,
  [194] = 1,
    ACTIONS(62), 1,
      sym_text,
  [198] = 1,
    ACTIONS(64), 1,
      sym_text,
  [202] = 1,
    ACTIONS(66), 1,
      sym_text,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(9)] = 0,
  [SMALL_STATE(10)] = 25,
  [SMALL_STATE(11)] = 50,
  [SMALL_STATE(12)] = 72,
  [SMALL_STATE(13)] = 94,
  [SMALL_STATE(14)] = 116,
  [SMALL_STATE(15)] = 133,
  [SMALL_STATE(16)] = 150,
  [SMALL_STATE(17)] = 167,
  [SMALL_STATE(18)] = 175,
  [SMALL_STATE(19)] = 182,
  [SMALL_STATE(20)] = 186,
  [SMALL_STATE(21)] = 190,
  [SMALL_STATE(22)] = 194,
  [SMALL_STATE(23)] = 198,
  [SMALL_STATE(24)] = 202,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [13] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_directive_repeat1, 2, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_directive_repeat1, 2, 0, 0),
  [17] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_directive_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [20] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_flag, 1, 0, 0),
  [22] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_flag, 1, 0, 0),
  [24] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [26] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [28] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__width_and_precision, 1, 0, 0),
  [30] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_width, 1, 0, 0),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__width_and_precision, 2, 0, 0),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_precision, 1, 0, 0),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__width_and_precision, 3, 0, 0),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_string, 1, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_string, 2, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_format_string_repeat1, 2, 0, 0),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_format_string_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_format_string_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [54] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_format_string_repeat1, 2, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [58] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_conversion_specifier, 1, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 2, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 3, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 4, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_lua_format_string(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "lua_format_string",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
