/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 33
#define LARGE_STATE_COUNT 9
#define SYMBOL_COUNT 48
#define ALIAS_COUNT 0
#define TOKEN_COUNT 36
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_PERCENT = 1,
  aux_sym_explicit_argument_index_token1 = 2,
  anon_sym_LBRACK = 3,
  anon_sym_RBRACK = 4,
  sym_asterisk = 5,
  aux_sym_precision_token1 = 6,
  anon_sym_DOT = 7,
  anon_sym_v = 8,
  anon_sym_T = 9,
  anon_sym_t = 10,
  anon_sym_b = 11,
  anon_sym_c = 12,
  anon_sym_d = 13,
  anon_sym_e = 14,
  anon_sym_E = 15,
  anon_sym_f = 16,
  anon_sym_F = 17,
  anon_sym_g = 18,
  anon_sym_G = 19,
  anon_sym_o = 20,
  anon_sym_O = 21,
  anon_sym_q = 22,
  anon_sym_x = 23,
  anon_sym_X = 24,
  anon_sym_U = 25,
  anon_sym_s = 26,
  anon_sym_p = 27,
  anon_sym_w = 28,
  sym_escaped_percent_sign = 29,
  anon_sym_PLUS = 30,
  anon_sym_DASH = 31,
  anon_sym_POUND = 32,
  anon_sym_SPACE = 33,
  anon_sym_0 = 34,
  sym_text = 35,
  sym_format_string = 36,
  sym__maybe_format = 37,
  sym_format_specifier = 38,
  sym_explicit_argument_index = 39,
  sym_explicit_argument_index_expr = 40,
  sym_width = 41,
  sym_precision = 42,
  sym__width_and_precision = 43,
  sym_verb = 44,
  sym_flag = 45,
  aux_sym_format_string_repeat1 = 46,
  aux_sym_format_specifier_repeat1 = 47,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_PERCENT] = "%",
  [aux_sym_explicit_argument_index_token1] = "explicit_argument_index_token1",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_asterisk] = "asterisk",
  [aux_sym_precision_token1] = "precision_token1",
  [anon_sym_DOT] = ".",
  [anon_sym_v] = "v",
  [anon_sym_T] = "T",
  [anon_sym_t] = "t",
  [anon_sym_b] = "b",
  [anon_sym_c] = "c",
  [anon_sym_d] = "d",
  [anon_sym_e] = "e",
  [anon_sym_E] = "E",
  [anon_sym_f] = "f",
  [anon_sym_F] = "F",
  [anon_sym_g] = "g",
  [anon_sym_G] = "G",
  [anon_sym_o] = "o",
  [anon_sym_O] = "O",
  [anon_sym_q] = "q",
  [anon_sym_x] = "x",
  [anon_sym_X] = "X",
  [anon_sym_U] = "U",
  [anon_sym_s] = "s",
  [anon_sym_p] = "p",
  [anon_sym_w] = "w",
  [sym_escaped_percent_sign] = "escaped_percent_sign",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_POUND] = "#",
  [anon_sym_SPACE] = " ",
  [anon_sym_0] = "0",
  [sym_text] = "text",
  [sym_format_string] = "format_string",
  [sym__maybe_format] = "_maybe_format",
  [sym_format_specifier] = "format_specifier",
  [sym_explicit_argument_index] = "explicit_argument_index",
  [sym_explicit_argument_index_expr] = "explicit_argument_index_expr",
  [sym_width] = "width",
  [sym_precision] = "precision",
  [sym__width_and_precision] = "_width_and_precision",
  [sym_verb] = "verb",
  [sym_flag] = "flag",
  [aux_sym_format_string_repeat1] = "format_string_repeat1",
  [aux_sym_format_specifier_repeat1] = "format_specifier_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [aux_sym_explicit_argument_index_token1] = aux_sym_explicit_argument_index_token1,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_asterisk] = sym_asterisk,
  [aux_sym_precision_token1] = aux_sym_precision_token1,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_v] = anon_sym_v,
  [anon_sym_T] = anon_sym_T,
  [anon_sym_t] = anon_sym_t,
  [anon_sym_b] = anon_sym_b,
  [anon_sym_c] = anon_sym_c,
  [anon_sym_d] = anon_sym_d,
  [anon_sym_e] = anon_sym_e,
  [anon_sym_E] = anon_sym_E,
  [anon_sym_f] = anon_sym_f,
  [anon_sym_F] = anon_sym_F,
  [anon_sym_g] = anon_sym_g,
  [anon_sym_G] = anon_sym_G,
  [anon_sym_o] = anon_sym_o,
  [anon_sym_O] = anon_sym_O,
  [anon_sym_q] = anon_sym_q,
  [anon_sym_x] = anon_sym_x,
  [anon_sym_X] = anon_sym_X,
  [anon_sym_U] = anon_sym_U,
  [anon_sym_s] = anon_sym_s,
  [anon_sym_p] = anon_sym_p,
  [anon_sym_w] = anon_sym_w,
  [sym_escaped_percent_sign] = sym_escaped_percent_sign,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_SPACE] = anon_sym_SPACE,
  [anon_sym_0] = anon_sym_0,
  [sym_text] = sym_text,
  [sym_format_string] = sym_format_string,
  [sym__maybe_format] = sym__maybe_format,
  [sym_format_specifier] = sym_format_specifier,
  [sym_explicit_argument_index] = sym_explicit_argument_index,
  [sym_explicit_argument_index_expr] = sym_explicit_argument_index_expr,
  [sym_width] = sym_width,
  [sym_precision] = sym_precision,
  [sym__width_and_precision] = sym__width_and_precision,
  [sym_verb] = sym_verb,
  [sym_flag] = sym_flag,
  [aux_sym_format_string_repeat1] = aux_sym_format_string_repeat1,
  [aux_sym_format_specifier_repeat1] = aux_sym_format_specifier_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_explicit_argument_index_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_asterisk] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_precision_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_v] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_T] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_t] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_b] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_c] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_d] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_e] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_E] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_f] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_F] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_g] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_G] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_o] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_O] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_q] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_x] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_X] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_U] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_s] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_p] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_w] = {
    .visible = true,
    .named = false,
  },
  [sym_escaped_percent_sign] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SPACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_0] = {
    .visible = true,
    .named = false,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_format_string] = {
    .visible = true,
    .named = true,
  },
  [sym__maybe_format] = {
    .visible = false,
    .named = true,
  },
  [sym_format_specifier] = {
    .visible = true,
    .named = true,
  },
  [sym_explicit_argument_index] = {
    .visible = true,
    .named = true,
  },
  [sym_explicit_argument_index_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_width] = {
    .visible = true,
    .named = true,
  },
  [sym_precision] = {
    .visible = true,
    .named = true,
  },
  [sym__width_and_precision] = {
    .visible = false,
    .named = true,
  },
  [sym_verb] = {
    .visible = true,
    .named = true,
  },
  [sym_flag] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_format_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_format_specifier_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(2);
      ADVANCE_MAP(
        ' ', 37,
        '#', 36,
        '%', 3,
        '*', 7,
        '+', 34,
        '-', 35,
        '.', 11,
        '0', 38,
        'E', 19,
        'F', 21,
        'G', 23,
        'O', 25,
        'T', 13,
        'U', 29,
        'X', 28,
        '[', 5,
        ']', 6,
        'b', 15,
        'c', 16,
        'd', 17,
        'e', 18,
        'f', 20,
        'g', 22,
        'o', 24,
        'p', 31,
        'q', 26,
        's', 30,
        't', 14,
        'v', 12,
        'w', 32,
        'x', 27,
      );
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(4);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '*', 7,
        '.', 11,
        'E', 19,
        'F', 21,
        'G', 23,
        'O', 25,
        'T', 13,
        'U', 29,
        'X', 28,
        'b', 15,
        'c', 16,
        'd', 17,
        'e', 18,
        'f', 20,
        'g', 22,
        'o', 24,
        'p', 31,
        'q', 26,
        's', 30,
        't', 14,
        'v', 12,
        'w', 32,
        'x', 27,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(4);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      if (lookahead == '%') ADVANCE(33);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(aux_sym_explicit_argument_index_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(4);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym_asterisk);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(aux_sym_precision_token1);
      ADVANCE_MAP(
        '*', 7,
        '.', 11,
        'E', 19,
        'F', 21,
        'G', 23,
        'O', 25,
        'T', 13,
        'U', 29,
        'X', 28,
        'b', 15,
        'c', 16,
        'd', 17,
        'e', 18,
        'f', 20,
        'g', 22,
        'o', 24,
        'p', 31,
        'q', 26,
        's', 30,
        't', 14,
        'v', 12,
        'w', 32,
        'x', 27,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(10);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(aux_sym_precision_token1);
      if (lookahead == '*') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(10);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(aux_sym_precision_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(10);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_v);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_T);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_t);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_b);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_c);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_d);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_e);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_E);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_f);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_F);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_g);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_G);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_o);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_O);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_q);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_x);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_X);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_U);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_s);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_p);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_w);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_escaped_percent_sign);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_SPACE);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(4);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '%') ADVANCE(39);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 39},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 8},
  [9] = {.lex_state = 8},
  [10] = {.lex_state = 8},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 9},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 39},
  [26] = {.lex_state = 39},
  [27] = {.lex_state = 39},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 39},
  [31] = {.lex_state = 39},
  [32] = {.lex_state = 39},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [aux_sym_explicit_argument_index_token1] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_asterisk] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_v] = ACTIONS(1),
    [anon_sym_T] = ACTIONS(1),
    [anon_sym_t] = ACTIONS(1),
    [anon_sym_b] = ACTIONS(1),
    [anon_sym_c] = ACTIONS(1),
    [anon_sym_d] = ACTIONS(1),
    [anon_sym_e] = ACTIONS(1),
    [anon_sym_E] = ACTIONS(1),
    [anon_sym_f] = ACTIONS(1),
    [anon_sym_F] = ACTIONS(1),
    [anon_sym_g] = ACTIONS(1),
    [anon_sym_G] = ACTIONS(1),
    [anon_sym_o] = ACTIONS(1),
    [anon_sym_O] = ACTIONS(1),
    [anon_sym_q] = ACTIONS(1),
    [anon_sym_x] = ACTIONS(1),
    [anon_sym_X] = ACTIONS(1),
    [anon_sym_U] = ACTIONS(1),
    [anon_sym_s] = ACTIONS(1),
    [anon_sym_p] = ACTIONS(1),
    [anon_sym_w] = ACTIONS(1),
    [sym_escaped_percent_sign] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_SPACE] = ACTIONS(1),
    [anon_sym_0] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_format_string] = STATE(24),
    [sym_text] = ACTIONS(3),
  },
  [STATE(2)] = {
    [sym_explicit_argument_index_expr] = STATE(7),
    [sym_width] = STATE(8),
    [sym__width_and_precision] = STATE(13),
    [sym_verb] = STATE(30),
    [sym_flag] = STATE(4),
    [aux_sym_format_specifier_repeat1] = STATE(4),
    [aux_sym_explicit_argument_index_token1] = ACTIONS(5),
    [anon_sym_LBRACK] = ACTIONS(7),
    [sym_asterisk] = ACTIONS(9),
    [anon_sym_DOT] = ACTIONS(11),
    [anon_sym_v] = ACTIONS(13),
    [anon_sym_T] = ACTIONS(13),
    [anon_sym_t] = ACTIONS(13),
    [anon_sym_b] = ACTIONS(13),
    [anon_sym_c] = ACTIONS(13),
    [anon_sym_d] = ACTIONS(13),
    [anon_sym_e] = ACTIONS(13),
    [anon_sym_E] = ACTIONS(13),
    [anon_sym_f] = ACTIONS(13),
    [anon_sym_F] = ACTIONS(13),
    [anon_sym_g] = ACTIONS(13),
    [anon_sym_G] = ACTIONS(13),
    [anon_sym_o] = ACTIONS(13),
    [anon_sym_O] = ACTIONS(13),
    [anon_sym_q] = ACTIONS(13),
    [anon_sym_x] = ACTIONS(13),
    [anon_sym_X] = ACTIONS(13),
    [anon_sym_U] = ACTIONS(13),
    [anon_sym_s] = ACTIONS(13),
    [anon_sym_p] = ACTIONS(13),
    [anon_sym_w] = ACTIONS(13),
    [anon_sym_PLUS] = ACTIONS(15),
    [anon_sym_DASH] = ACTIONS(15),
    [anon_sym_POUND] = ACTIONS(15),
    [anon_sym_SPACE] = ACTIONS(15),
    [anon_sym_0] = ACTIONS(17),
  },
  [STATE(3)] = {
    [sym_explicit_argument_index_expr] = STATE(6),
    [sym_width] = STATE(8),
    [sym__width_and_precision] = STATE(12),
    [sym_verb] = STATE(27),
    [sym_flag] = STATE(2),
    [aux_sym_format_specifier_repeat1] = STATE(2),
    [aux_sym_explicit_argument_index_token1] = ACTIONS(5),
    [anon_sym_LBRACK] = ACTIONS(7),
    [sym_asterisk] = ACTIONS(9),
    [anon_sym_DOT] = ACTIONS(11),
    [anon_sym_v] = ACTIONS(13),
    [anon_sym_T] = ACTIONS(13),
    [anon_sym_t] = ACTIONS(13),
    [anon_sym_b] = ACTIONS(13),
    [anon_sym_c] = ACTIONS(13),
    [anon_sym_d] = ACTIONS(13),
    [anon_sym_e] = ACTIONS(13),
    [anon_sym_E] = ACTIONS(13),
    [anon_sym_f] = ACTIONS(13),
    [anon_sym_F] = ACTIONS(13),
    [anon_sym_g] = ACTIONS(13),
    [anon_sym_G] = ACTIONS(13),
    [anon_sym_o] = ACTIONS(13),
    [anon_sym_O] = ACTIONS(13),
    [anon_sym_q] = ACTIONS(13),
    [anon_sym_x] = ACTIONS(13),
    [anon_sym_X] = ACTIONS(13),
    [anon_sym_U] = ACTIONS(13),
    [anon_sym_s] = ACTIONS(13),
    [anon_sym_p] = ACTIONS(13),
    [anon_sym_w] = ACTIONS(13),
    [anon_sym_PLUS] = ACTIONS(15),
    [anon_sym_DASH] = ACTIONS(15),
    [anon_sym_POUND] = ACTIONS(15),
    [anon_sym_SPACE] = ACTIONS(15),
    [anon_sym_0] = ACTIONS(17),
  },
  [STATE(4)] = {
    [sym_flag] = STATE(4),
    [aux_sym_format_specifier_repeat1] = STATE(4),
    [aux_sym_explicit_argument_index_token1] = ACTIONS(19),
    [anon_sym_LBRACK] = ACTIONS(21),
    [sym_asterisk] = ACTIONS(21),
    [anon_sym_DOT] = ACTIONS(21),
    [anon_sym_v] = ACTIONS(21),
    [anon_sym_T] = ACTIONS(21),
    [anon_sym_t] = ACTIONS(21),
    [anon_sym_b] = ACTIONS(21),
    [anon_sym_c] = ACTIONS(21),
    [anon_sym_d] = ACTIONS(21),
    [anon_sym_e] = ACTIONS(21),
    [anon_sym_E] = ACTIONS(21),
    [anon_sym_f] = ACTIONS(21),
    [anon_sym_F] = ACTIONS(21),
    [anon_sym_g] = ACTIONS(21),
    [anon_sym_G] = ACTIONS(21),
    [anon_sym_o] = ACTIONS(21),
    [anon_sym_O] = ACTIONS(21),
    [anon_sym_q] = ACTIONS(21),
    [anon_sym_x] = ACTIONS(21),
    [anon_sym_X] = ACTIONS(21),
    [anon_sym_U] = ACTIONS(21),
    [anon_sym_s] = ACTIONS(21),
    [anon_sym_p] = ACTIONS(21),
    [anon_sym_w] = ACTIONS(21),
    [anon_sym_PLUS] = ACTIONS(23),
    [anon_sym_DASH] = ACTIONS(23),
    [anon_sym_POUND] = ACTIONS(23),
    [anon_sym_SPACE] = ACTIONS(23),
    [anon_sym_0] = ACTIONS(26),
  },
  [STATE(5)] = {
    [aux_sym_explicit_argument_index_token1] = ACTIONS(29),
    [anon_sym_LBRACK] = ACTIONS(31),
    [sym_asterisk] = ACTIONS(31),
    [anon_sym_DOT] = ACTIONS(31),
    [anon_sym_v] = ACTIONS(31),
    [anon_sym_T] = ACTIONS(31),
    [anon_sym_t] = ACTIONS(31),
    [anon_sym_b] = ACTIONS(31),
    [anon_sym_c] = ACTIONS(31),
    [anon_sym_d] = ACTIONS(31),
    [anon_sym_e] = ACTIONS(31),
    [anon_sym_E] = ACTIONS(31),
    [anon_sym_f] = ACTIONS(31),
    [anon_sym_F] = ACTIONS(31),
    [anon_sym_g] = ACTIONS(31),
    [anon_sym_G] = ACTIONS(31),
    [anon_sym_o] = ACTIONS(31),
    [anon_sym_O] = ACTIONS(31),
    [anon_sym_q] = ACTIONS(31),
    [anon_sym_x] = ACTIONS(31),
    [anon_sym_X] = ACTIONS(31),
    [anon_sym_U] = ACTIONS(31),
    [anon_sym_s] = ACTIONS(31),
    [anon_sym_p] = ACTIONS(31),
    [anon_sym_w] = ACTIONS(31),
    [anon_sym_PLUS] = ACTIONS(31),
    [anon_sym_DASH] = ACTIONS(31),
    [anon_sym_POUND] = ACTIONS(31),
    [anon_sym_SPACE] = ACTIONS(31),
    [anon_sym_0] = ACTIONS(29),
  },
  [STATE(6)] = {
    [sym_width] = STATE(8),
    [sym__width_and_precision] = STATE(13),
    [sym_verb] = STATE(30),
    [aux_sym_explicit_argument_index_token1] = ACTIONS(9),
    [sym_asterisk] = ACTIONS(9),
    [anon_sym_DOT] = ACTIONS(11),
    [anon_sym_v] = ACTIONS(13),
    [anon_sym_T] = ACTIONS(13),
    [anon_sym_t] = ACTIONS(13),
    [anon_sym_b] = ACTIONS(13),
    [anon_sym_c] = ACTIONS(13),
    [anon_sym_d] = ACTIONS(13),
    [anon_sym_e] = ACTIONS(13),
    [anon_sym_E] = ACTIONS(13),
    [anon_sym_f] = ACTIONS(13),
    [anon_sym_F] = ACTIONS(13),
    [anon_sym_g] = ACTIONS(13),
    [anon_sym_G] = ACTIONS(13),
    [anon_sym_o] = ACTIONS(13),
    [anon_sym_O] = ACTIONS(13),
    [anon_sym_q] = ACTIONS(13),
    [anon_sym_x] = ACTIONS(13),
    [anon_sym_X] = ACTIONS(13),
    [anon_sym_U] = ACTIONS(13),
    [anon_sym_s] = ACTIONS(13),
    [anon_sym_p] = ACTIONS(13),
    [anon_sym_w] = ACTIONS(13),
  },
  [STATE(7)] = {
    [sym_width] = STATE(8),
    [sym__width_and_precision] = STATE(14),
    [sym_verb] = STATE(31),
    [aux_sym_explicit_argument_index_token1] = ACTIONS(9),
    [sym_asterisk] = ACTIONS(9),
    [anon_sym_DOT] = ACTIONS(11),
    [anon_sym_v] = ACTIONS(13),
    [anon_sym_T] = ACTIONS(13),
    [anon_sym_t] = ACTIONS(13),
    [anon_sym_b] = ACTIONS(13),
    [anon_sym_c] = ACTIONS(13),
    [anon_sym_d] = ACTIONS(13),
    [anon_sym_e] = ACTIONS(13),
    [anon_sym_E] = ACTIONS(13),
    [anon_sym_f] = ACTIONS(13),
    [anon_sym_F] = ACTIONS(13),
    [anon_sym_g] = ACTIONS(13),
    [anon_sym_G] = ACTIONS(13),
    [anon_sym_o] = ACTIONS(13),
    [anon_sym_O] = ACTIONS(13),
    [anon_sym_q] = ACTIONS(13),
    [anon_sym_x] = ACTIONS(13),
    [anon_sym_X] = ACTIONS(13),
    [anon_sym_U] = ACTIONS(13),
    [anon_sym_s] = ACTIONS(13),
    [anon_sym_p] = ACTIONS(13),
    [anon_sym_w] = ACTIONS(13),
  },
  [STATE(8)] = {
    [sym_precision] = STATE(16),
    [sym_asterisk] = ACTIONS(33),
    [aux_sym_precision_token1] = ACTIONS(35),
    [anon_sym_DOT] = ACTIONS(37),
    [anon_sym_v] = ACTIONS(39),
    [anon_sym_T] = ACTIONS(39),
    [anon_sym_t] = ACTIONS(39),
    [anon_sym_b] = ACTIONS(39),
    [anon_sym_c] = ACTIONS(39),
    [anon_sym_d] = ACTIONS(39),
    [anon_sym_e] = ACTIONS(39),
    [anon_sym_E] = ACTIONS(39),
    [anon_sym_f] = ACTIONS(39),
    [anon_sym_F] = ACTIONS(39),
    [anon_sym_g] = ACTIONS(39),
    [anon_sym_G] = ACTIONS(39),
    [anon_sym_o] = ACTIONS(39),
    [anon_sym_O] = ACTIONS(39),
    [anon_sym_q] = ACTIONS(39),
    [anon_sym_x] = ACTIONS(39),
    [anon_sym_X] = ACTIONS(39),
    [anon_sym_U] = ACTIONS(39),
    [anon_sym_s] = ACTIONS(39),
    [anon_sym_p] = ACTIONS(39),
    [anon_sym_w] = ACTIONS(39),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(43), 1,
      aux_sym_precision_token1,
    ACTIONS(41), 23,
      sym_asterisk,
      anon_sym_DOT,
      anon_sym_v,
      anon_sym_T,
      anon_sym_t,
      anon_sym_b,
      anon_sym_c,
      anon_sym_d,
      anon_sym_e,
      anon_sym_E,
      anon_sym_f,
      anon_sym_F,
      anon_sym_g,
      anon_sym_G,
      anon_sym_o,
      anon_sym_O,
      anon_sym_q,
      anon_sym_x,
      anon_sym_X,
      anon_sym_U,
      anon_sym_s,
      anon_sym_p,
      anon_sym_w,
  [29] = 4,
    ACTIONS(33), 1,
      sym_asterisk,
    ACTIONS(35), 1,
      aux_sym_precision_token1,
    STATE(15), 1,
      sym_precision,
    ACTIONS(45), 21,
      anon_sym_v,
      anon_sym_T,
      anon_sym_t,
      anon_sym_b,
      anon_sym_c,
      anon_sym_d,
      anon_sym_e,
      anon_sym_E,
      anon_sym_f,
      anon_sym_F,
      anon_sym_g,
      anon_sym_G,
      anon_sym_o,
      anon_sym_O,
      anon_sym_q,
      anon_sym_x,
      anon_sym_X,
      anon_sym_U,
      anon_sym_s,
      anon_sym_p,
      anon_sym_w,
  [62] = 1,
    ACTIONS(47), 24,
      aux_sym_explicit_argument_index_token1,
      sym_asterisk,
      anon_sym_DOT,
      anon_sym_v,
      anon_sym_T,
      anon_sym_t,
      anon_sym_b,
      anon_sym_c,
      anon_sym_d,
      anon_sym_e,
      anon_sym_E,
      anon_sym_f,
      anon_sym_F,
      anon_sym_g,
      anon_sym_G,
      anon_sym_o,
      anon_sym_O,
      anon_sym_q,
      anon_sym_x,
      anon_sym_X,
      anon_sym_U,
      anon_sym_s,
      anon_sym_p,
      anon_sym_w,
  [89] = 2,
    STATE(30), 1,
      sym_verb,
    ACTIONS(13), 21,
      anon_sym_v,
      anon_sym_T,
      anon_sym_t,
      anon_sym_b,
      anon_sym_c,
      anon_sym_d,
      anon_sym_e,
      anon_sym_E,
      anon_sym_f,
      anon_sym_F,
      anon_sym_g,
      anon_sym_G,
      anon_sym_o,
      anon_sym_O,
      anon_sym_q,
      anon_sym_x,
      anon_sym_X,
      anon_sym_U,
      anon_sym_s,
      anon_sym_p,
      anon_sym_w,
  [116] = 2,
    STATE(31), 1,
      sym_verb,
    ACTIONS(13), 21,
      anon_sym_v,
      anon_sym_T,
      anon_sym_t,
      anon_sym_b,
      anon_sym_c,
      anon_sym_d,
      anon_sym_e,
      anon_sym_E,
      anon_sym_f,
      anon_sym_F,
      anon_sym_g,
      anon_sym_G,
      anon_sym_o,
      anon_sym_O,
      anon_sym_q,
      anon_sym_x,
      anon_sym_X,
      anon_sym_U,
      anon_sym_s,
      anon_sym_p,
      anon_sym_w,
  [143] = 2,
    STATE(32), 1,
      sym_verb,
    ACTIONS(13), 21,
      anon_sym_v,
      anon_sym_T,
      anon_sym_t,
      anon_sym_b,
      anon_sym_c,
      anon_sym_d,
      anon_sym_e,
      anon_sym_E,
      anon_sym_f,
      anon_sym_F,
      anon_sym_g,
      anon_sym_G,
      anon_sym_o,
      anon_sym_O,
      anon_sym_q,
      anon_sym_x,
      anon_sym_X,
      anon_sym_U,
      anon_sym_s,
      anon_sym_p,
      anon_sym_w,
  [170] = 1,
    ACTIONS(49), 21,
      anon_sym_v,
      anon_sym_T,
      anon_sym_t,
      anon_sym_b,
      anon_sym_c,
      anon_sym_d,
      anon_sym_e,
      anon_sym_E,
      anon_sym_f,
      anon_sym_F,
      anon_sym_g,
      anon_sym_G,
      anon_sym_o,
      anon_sym_O,
      anon_sym_q,
      anon_sym_x,
      anon_sym_X,
      anon_sym_U,
      anon_sym_s,
      anon_sym_p,
      anon_sym_w,
  [194] = 1,
    ACTIONS(45), 21,
      anon_sym_v,
      anon_sym_T,
      anon_sym_t,
      anon_sym_b,
      anon_sym_c,
      anon_sym_d,
      anon_sym_e,
      anon_sym_E,
      anon_sym_f,
      anon_sym_F,
      anon_sym_g,
      anon_sym_G,
      anon_sym_o,
      anon_sym_O,
      anon_sym_q,
      anon_sym_x,
      anon_sym_X,
      anon_sym_U,
      anon_sym_s,
      anon_sym_p,
      anon_sym_w,
  [218] = 1,
    ACTIONS(51), 21,
      anon_sym_v,
      anon_sym_T,
      anon_sym_t,
      anon_sym_b,
      anon_sym_c,
      anon_sym_d,
      anon_sym_e,
      anon_sym_E,
      anon_sym_f,
      anon_sym_F,
      anon_sym_g,
      anon_sym_G,
      anon_sym_o,
      anon_sym_O,
      anon_sym_q,
      anon_sym_x,
      anon_sym_X,
      anon_sym_U,
      anon_sym_s,
      anon_sym_p,
      anon_sym_w,
  [242] = 5,
    ACTIONS(53), 1,
      ts_builtin_sym_end,
    ACTIONS(55), 1,
      anon_sym_PERCENT,
    ACTIONS(57), 1,
      sym_escaped_percent_sign,
    STATE(20), 1,
      aux_sym_format_string_repeat1,
    STATE(25), 2,
      sym__maybe_format,
      sym_format_specifier,
  [259] = 5,
    ACTIONS(55), 1,
      anon_sym_PERCENT,
    ACTIONS(57), 1,
      sym_escaped_percent_sign,
    ACTIONS(59), 1,
      ts_builtin_sym_end,
    STATE(18), 1,
      aux_sym_format_string_repeat1,
    STATE(25), 2,
      sym__maybe_format,
      sym_format_specifier,
  [276] = 5,
    ACTIONS(61), 1,
      ts_builtin_sym_end,
    ACTIONS(63), 1,
      anon_sym_PERCENT,
    ACTIONS(66), 1,
      sym_escaped_percent_sign,
    STATE(20), 1,
      aux_sym_format_string_repeat1,
    STATE(25), 2,
      sym__maybe_format,
      sym_format_specifier,
  [293] = 3,
    ACTIONS(33), 1,
      sym_asterisk,
    ACTIONS(35), 1,
      aux_sym_precision_token1,
    STATE(16), 1,
      sym_precision,
  [303] = 2,
    ACTIONS(69), 1,
      anon_sym_PERCENT,
    ACTIONS(61), 2,
      ts_builtin_sym_end,
      sym_escaped_percent_sign,
  [311] = 2,
    ACTIONS(71), 1,
      aux_sym_explicit_argument_index_token1,
    STATE(28), 1,
      sym_explicit_argument_index,
  [318] = 1,
    ACTIONS(73), 1,
      ts_builtin_sym_end,
  [322] = 1,
    ACTIONS(75), 1,
      sym_text,
  [326] = 1,
    ACTIONS(77), 1,
      sym_text,
  [330] = 1,
    ACTIONS(79), 1,
      sym_text,
  [334] = 1,
    ACTIONS(81), 1,
      anon_sym_RBRACK,
  [338] = 1,
    ACTIONS(83), 1,
      anon_sym_RBRACK,
  [342] = 1,
    ACTIONS(85), 1,
      sym_text,
  [346] = 1,
    ACTIONS(87), 1,
      sym_text,
  [350] = 1,
    ACTIONS(89), 1,
      sym_text,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(9)] = 0,
  [SMALL_STATE(10)] = 29,
  [SMALL_STATE(11)] = 62,
  [SMALL_STATE(12)] = 89,
  [SMALL_STATE(13)] = 116,
  [SMALL_STATE(14)] = 143,
  [SMALL_STATE(15)] = 170,
  [SMALL_STATE(16)] = 194,
  [SMALL_STATE(17)] = 218,
  [SMALL_STATE(18)] = 242,
  [SMALL_STATE(19)] = 259,
  [SMALL_STATE(20)] = 276,
  [SMALL_STATE(21)] = 293,
  [SMALL_STATE(22)] = 303,
  [SMALL_STATE(23)] = 311,
  [SMALL_STATE(24)] = 318,
  [SMALL_STATE(25)] = 322,
  [SMALL_STATE(26)] = 326,
  [SMALL_STATE(27)] = 330,
  [SMALL_STATE(28)] = 334,
  [SMALL_STATE(29)] = 338,
  [SMALL_STATE(30)] = 342,
  [SMALL_STATE(31)] = 346,
  [SMALL_STATE(32)] = 350,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [19] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_format_specifier_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_format_specifier_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_format_specifier_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [26] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_format_specifier_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [29] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_flag, 1, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_flag, 1, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__width_and_precision, 1, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_width, 1, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_width, 1, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__width_and_precision, 2, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_explicit_argument_index_expr, 3, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__width_and_precision, 3, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_precision, 1, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_string, 2, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_string, 1, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_format_string_repeat1, 2, 0, 0),
  [63] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_format_string_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [66] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_format_string_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_format_string_repeat1, 2, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [73] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_verb, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifier, 2, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_explicit_argument_index, 1, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifier, 3, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifier, 4, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifier, 5, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_go_format_string(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "go_format_string",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
