/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 45
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 49
#define ALIAS_COUNT 0
#define TOKEN_COUNT 28
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_disable = 1,
  anon_sym_EQ = 2,
  anon_sym_enable = 3,
  anon_sym_extended_DASHanalysis = 4,
  anon_sym_external_DASHsources = 5,
  anon_sym_source = 6,
  anon_sym_source_DASHpath = 7,
  anon_sym_shell = 8,
  sym_all = 9,
  anon_sym_sh = 10,
  anon_sym_bash = 11,
  anon_sym_dash = 12,
  anon_sym_ksh = 13,
  anon_sym_busybox = 14,
  anon_sym_SC = 15,
  anon_sym_COMMA = 16,
  anon_sym_DASH = 17,
  sym_integer = 18,
  anon_sym_true = 19,
  anon_sym_false = 20,
  anon_sym_SQUOTE = 21,
  aux_sym_string_token1 = 22,
  anon_sym_DQUOTE = 23,
  aux_sym_string_token2 = 24,
  aux_sym_identifier_token1 = 25,
  sym_comment = 26,
  sym__whitespace = 27,
  sym_shellcheckrc_file = 28,
  sym__directive = 29,
  sym__disable_value = 30,
  sym_disable_directive = 31,
  sym_enable_directive = 32,
  sym_extended_analysis_directive = 33,
  sym_external_sources_directive = 34,
  sym__source_value = 35,
  sym_source_directive = 36,
  sym_source_path_directive = 37,
  sym_shell_directive = 38,
  sym_shell = 39,
  sym_rule_id = 40,
  sym__rule_id = 41,
  sym__rule_id_list = 42,
  sym_rule_id_range = 43,
  sym_boolean = 44,
  sym_string = 45,
  sym_identifier = 46,
  aux_sym_shellcheckrc_file_repeat1 = 47,
  aux_sym__rule_id_list_repeat1 = 48,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_disable] = "disable",
  [anon_sym_EQ] = "=",
  [anon_sym_enable] = "enable",
  [anon_sym_extended_DASHanalysis] = "extended-analysis",
  [anon_sym_external_DASHsources] = "external-sources",
  [anon_sym_source] = "source",
  [anon_sym_source_DASHpath] = "source-path",
  [anon_sym_shell] = "shell",
  [sym_all] = "all",
  [anon_sym_sh] = "sh",
  [anon_sym_bash] = "bash",
  [anon_sym_dash] = "dash",
  [anon_sym_ksh] = "ksh",
  [anon_sym_busybox] = "busybox",
  [anon_sym_SC] = "SC",
  [anon_sym_COMMA] = ",",
  [anon_sym_DASH] = "-",
  [sym_integer] = "integer",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_string_token1] = "string_token1",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token2] = "string_token2",
  [aux_sym_identifier_token1] = "identifier_token1",
  [sym_comment] = "comment",
  [sym__whitespace] = "_whitespace",
  [sym_shellcheckrc_file] = "shellcheckrc_file",
  [sym__directive] = "_directive",
  [sym__disable_value] = "_disable_value",
  [sym_disable_directive] = "disable_directive",
  [sym_enable_directive] = "enable_directive",
  [sym_extended_analysis_directive] = "extended_analysis_directive",
  [sym_external_sources_directive] = "external_sources_directive",
  [sym__source_value] = "_source_value",
  [sym_source_directive] = "source_directive",
  [sym_source_path_directive] = "source_path_directive",
  [sym_shell_directive] = "shell_directive",
  [sym_shell] = "shell",
  [sym_rule_id] = "rule_id",
  [sym__rule_id] = "_rule_id",
  [sym__rule_id_list] = "_rule_id_list",
  [sym_rule_id_range] = "rule_id_range",
  [sym_boolean] = "boolean",
  [sym_string] = "string",
  [sym_identifier] = "identifier",
  [aux_sym_shellcheckrc_file_repeat1] = "shellcheckrc_file_repeat1",
  [aux_sym__rule_id_list_repeat1] = "_rule_id_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_disable] = anon_sym_disable,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_enable] = anon_sym_enable,
  [anon_sym_extended_DASHanalysis] = anon_sym_extended_DASHanalysis,
  [anon_sym_external_DASHsources] = anon_sym_external_DASHsources,
  [anon_sym_source] = anon_sym_source,
  [anon_sym_source_DASHpath] = anon_sym_source_DASHpath,
  [anon_sym_shell] = anon_sym_shell,
  [sym_all] = sym_all,
  [anon_sym_sh] = anon_sym_sh,
  [anon_sym_bash] = anon_sym_bash,
  [anon_sym_dash] = anon_sym_dash,
  [anon_sym_ksh] = anon_sym_ksh,
  [anon_sym_busybox] = anon_sym_busybox,
  [anon_sym_SC] = anon_sym_SC,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_DASH] = anon_sym_DASH,
  [sym_integer] = sym_integer,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token2] = aux_sym_string_token2,
  [aux_sym_identifier_token1] = aux_sym_identifier_token1,
  [sym_comment] = sym_comment,
  [sym__whitespace] = sym__whitespace,
  [sym_shellcheckrc_file] = sym_shellcheckrc_file,
  [sym__directive] = sym__directive,
  [sym__disable_value] = sym__disable_value,
  [sym_disable_directive] = sym_disable_directive,
  [sym_enable_directive] = sym_enable_directive,
  [sym_extended_analysis_directive] = sym_extended_analysis_directive,
  [sym_external_sources_directive] = sym_external_sources_directive,
  [sym__source_value] = sym__source_value,
  [sym_source_directive] = sym_source_directive,
  [sym_source_path_directive] = sym_source_path_directive,
  [sym_shell_directive] = sym_shell_directive,
  [sym_shell] = sym_shell,
  [sym_rule_id] = sym_rule_id,
  [sym__rule_id] = sym__rule_id,
  [sym__rule_id_list] = sym__rule_id_list,
  [sym_rule_id_range] = sym_rule_id_range,
  [sym_boolean] = sym_boolean,
  [sym_string] = sym_string,
  [sym_identifier] = sym_identifier,
  [aux_sym_shellcheckrc_file_repeat1] = aux_sym_shellcheckrc_file_repeat1,
  [aux_sym__rule_id_list_repeat1] = aux_sym__rule_id_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_disable] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_enable] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_extended_DASHanalysis] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_external_DASHsources] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_source] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_source_DASHpath] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_shell] = {
    .visible = true,
    .named = false,
  },
  [sym_all] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_sh] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bash] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_dash] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ksh] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_busybox] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SC] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_identifier_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__whitespace] = {
    .visible = false,
    .named = true,
  },
  [sym_shellcheckrc_file] = {
    .visible = true,
    .named = true,
  },
  [sym__directive] = {
    .visible = false,
    .named = true,
  },
  [sym__disable_value] = {
    .visible = false,
    .named = true,
  },
  [sym_disable_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_enable_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_extended_analysis_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_external_sources_directive] = {
    .visible = true,
    .named = true,
  },
  [sym__source_value] = {
    .visible = false,
    .named = true,
  },
  [sym_source_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_source_path_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_shell_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_shell] = {
    .visible = true,
    .named = true,
  },
  [sym_rule_id] = {
    .visible = true,
    .named = true,
  },
  [sym__rule_id] = {
    .visible = false,
    .named = true,
  },
  [sym__rule_id_list] = {
    .visible = false,
    .named = true,
  },
  [sym_rule_id_range] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_shellcheckrc_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__rule_id_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_from = 1,
  field_id = 2,
  field_to = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_from] = "from",
  [field_id] = "id",
  [field_to] = "to",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_id, 0},
  [1] =
    {field_id, 1},
  [2] =
    {field_from, 0},
    {field_to, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(77);
      ADVANCE_MAP(
        '"', 103,
        '#', 111,
        '\'', 98,
        ',', 93,
        '-', 94,
        '=', 79,
        'S', 5,
        'a', 41,
        'b', 11,
        'd', 12,
        'e', 49,
        'f', 8,
        'k', 58,
        's', 31,
        't', 56,
        '\t', 112,
        '\n', 112,
        '\r', 112,
        ' ', 112,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(95);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(103);
      if (lookahead == '#') ADVANCE(111);
      if (lookahead == '\'') ADVANCE(98);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(112);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 2:
      if (lookahead == '#') ADVANCE(111);
      if (lookahead == 'a') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(112);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 3:
      if (lookahead == '-') ADVANCE(14);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(64);
      END_STATE();
    case 5:
      if (lookahead == 'C') ADVANCE(92);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(16);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(69);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(44);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(43);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(42);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(63);
      if (lookahead == 'u') ADVANCE(59);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(65);
      if (lookahead == 'i') ADVANCE(67);
      END_STATE();
    case 13:
      if (lookahead == 'a') ADVANCE(17);
      END_STATE();
    case 14:
      if (lookahead == 'a') ADVANCE(51);
      END_STATE();
    case 15:
      if (lookahead == 'b') ADVANCE(52);
      END_STATE();
    case 16:
      if (lookahead == 'b') ADVANCE(45);
      END_STATE();
    case 17:
      if (lookahead == 'b') ADVANCE(46);
      END_STATE();
    case 18:
      if (lookahead == 'c') ADVANCE(26);
      END_STATE();
    case 19:
      if (lookahead == 'c') ADVANCE(29);
      END_STATE();
    case 20:
      if (lookahead == 'd') ADVANCE(3);
      END_STATE();
    case 21:
      if (lookahead == 'd') ADVANCE(28);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(48);
      END_STATE();
    case 23:
      if (lookahead == 'e') ADVANCE(96);
      END_STATE();
    case 24:
      if (lookahead == 'e') ADVANCE(97);
      END_STATE();
    case 25:
      if (lookahead == 'e') ADVANCE(80);
      END_STATE();
    case 26:
      if (lookahead == 'e') ADVANCE(83);
      END_STATE();
    case 27:
      if (lookahead == 'e') ADVANCE(78);
      END_STATE();
    case 28:
      if (lookahead == 'e') ADVANCE(20);
      END_STATE();
    case 29:
      if (lookahead == 'e') ADVANCE(61);
      END_STATE();
    case 30:
      if (lookahead == 'e') ADVANCE(47);
      END_STATE();
    case 31:
      if (lookahead == 'h') ADVANCE(87);
      if (lookahead == 'o') ADVANCE(70);
      END_STATE();
    case 32:
      if (lookahead == 'h') ADVANCE(90);
      END_STATE();
    case 33:
      if (lookahead == 'h') ADVANCE(88);
      END_STATE();
    case 34:
      if (lookahead == 'h') ADVANCE(89);
      END_STATE();
    case 35:
      if (lookahead == 'h') ADVANCE(84);
      END_STATE();
    case 36:
      if (lookahead == 'h') ADVANCE(30);
      if (lookahead == 'o') ADVANCE(70);
      END_STATE();
    case 37:
      if (lookahead == 'i') ADVANCE(67);
      END_STATE();
    case 38:
      if (lookahead == 'i') ADVANCE(62);
      END_STATE();
    case 39:
      if (lookahead == 'l') ADVANCE(86);
      END_STATE();
    case 40:
      if (lookahead == 'l') ADVANCE(85);
      END_STATE();
    case 41:
      if (lookahead == 'l') ADVANCE(39);
      END_STATE();
    case 42:
      if (lookahead == 'l') ADVANCE(75);
      END_STATE();
    case 43:
      if (lookahead == 'l') ADVANCE(4);
      END_STATE();
    case 44:
      if (lookahead == 'l') ADVANCE(66);
      END_STATE();
    case 45:
      if (lookahead == 'l') ADVANCE(25);
      END_STATE();
    case 46:
      if (lookahead == 'l') ADVANCE(27);
      END_STATE();
    case 47:
      if (lookahead == 'l') ADVANCE(40);
      END_STATE();
    case 48:
      if (lookahead == 'n') ADVANCE(21);
      if (lookahead == 'r') ADVANCE(50);
      END_STATE();
    case 49:
      if (lookahead == 'n') ADVANCE(6);
      if (lookahead == 'x') ADVANCE(68);
      END_STATE();
    case 50:
      if (lookahead == 'n') ADVANCE(9);
      END_STATE();
    case 51:
      if (lookahead == 'n') ADVANCE(10);
      END_STATE();
    case 52:
      if (lookahead == 'o') ADVANCE(73);
      END_STATE();
    case 53:
      if (lookahead == 'o') ADVANCE(72);
      END_STATE();
    case 54:
      if (lookahead == 'p') ADVANCE(7);
      END_STATE();
    case 55:
      if (lookahead == 'r') ADVANCE(18);
      END_STATE();
    case 56:
      if (lookahead == 'r') ADVANCE(71);
      END_STATE();
    case 57:
      if (lookahead == 'r') ADVANCE(19);
      END_STATE();
    case 58:
      if (lookahead == 's') ADVANCE(32);
      END_STATE();
    case 59:
      if (lookahead == 's') ADVANCE(74);
      END_STATE();
    case 60:
      if (lookahead == 's') ADVANCE(38);
      END_STATE();
    case 61:
      if (lookahead == 's') ADVANCE(82);
      END_STATE();
    case 62:
      if (lookahead == 's') ADVANCE(81);
      END_STATE();
    case 63:
      if (lookahead == 's') ADVANCE(33);
      END_STATE();
    case 64:
      if (lookahead == 's') ADVANCE(53);
      END_STATE();
    case 65:
      if (lookahead == 's') ADVANCE(34);
      END_STATE();
    case 66:
      if (lookahead == 's') ADVANCE(24);
      END_STATE();
    case 67:
      if (lookahead == 's') ADVANCE(13);
      END_STATE();
    case 68:
      if (lookahead == 't') ADVANCE(22);
      END_STATE();
    case 69:
      if (lookahead == 't') ADVANCE(35);
      END_STATE();
    case 70:
      if (lookahead == 'u') ADVANCE(55);
      END_STATE();
    case 71:
      if (lookahead == 'u') ADVANCE(23);
      END_STATE();
    case 72:
      if (lookahead == 'u') ADVANCE(57);
      END_STATE();
    case 73:
      if (lookahead == 'x') ADVANCE(91);
      END_STATE();
    case 74:
      if (lookahead == 'y') ADVANCE(15);
      END_STATE();
    case 75:
      if (lookahead == 'y') ADVANCE(60);
      END_STATE();
    case 76:
      if (eof) ADVANCE(77);
      ADVANCE_MAP(
        '#', 111,
        ',', 93,
        '-', 94,
        'd', 37,
        'e', 49,
        's', 36,
        '\t', 112,
        '\n', 112,
        '\r', 112,
        ' ', 112,
      );
      END_STATE();
    case 77:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_disable);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_enable);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_extended_DASHanalysis);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_external_DASHsources);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_source);
      if (lookahead == '-') ADVANCE(54);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_source_DASHpath);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_shell);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_all);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_sh);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_bash);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_dash);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_ksh);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_busybox);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_SC);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(95);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '\n') ADVANCE(102);
      if (lookahead == '\'') ADVANCE(111);
      if (lookahead != 0) ADVANCE(99);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '#') ADVANCE(99);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(101);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(102);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(101);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(102);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(102);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '\n') ADVANCE(107);
      if (lookahead == '"') ADVANCE(111);
      if (lookahead != 0) ADVANCE(104);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '#') ADVANCE(104);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(106);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '#') ADVANCE(107);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(106);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(107);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(107);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(aux_sym_identifier_token1);
      if (lookahead == 'l') ADVANCE(86);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(aux_sym_identifier_token1);
      if (lookahead == 'l') ADVANCE(108);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(aux_sym_identifier_token1);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(111);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym__whitespace);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(112);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 76},
  [2] = {.lex_state = 76},
  [3] = {.lex_state = 76},
  [4] = {.lex_state = 76},
  [5] = {.lex_state = 76},
  [6] = {.lex_state = 76},
  [7] = {.lex_state = 76},
  [8] = {.lex_state = 76},
  [9] = {.lex_state = 76},
  [10] = {.lex_state = 76},
  [11] = {.lex_state = 76},
  [12] = {.lex_state = 76},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 76},
  [15] = {.lex_state = 76},
  [16] = {.lex_state = 76},
  [17] = {.lex_state = 76},
  [18] = {.lex_state = 76},
  [19] = {.lex_state = 76},
  [20] = {.lex_state = 76},
  [21] = {.lex_state = 76},
  [22] = {.lex_state = 76},
  [23] = {.lex_state = 76},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 100},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 105},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_disable] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_enable] = ACTIONS(1),
    [anon_sym_extended_DASHanalysis] = ACTIONS(1),
    [anon_sym_external_DASHsources] = ACTIONS(1),
    [anon_sym_source] = ACTIONS(1),
    [anon_sym_source_DASHpath] = ACTIONS(1),
    [sym_all] = ACTIONS(1),
    [anon_sym_sh] = ACTIONS(1),
    [anon_sym_bash] = ACTIONS(1),
    [anon_sym_dash] = ACTIONS(1),
    [anon_sym_ksh] = ACTIONS(1),
    [anon_sym_busybox] = ACTIONS(1),
    [anon_sym_SC] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym__whitespace] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_shellcheckrc_file] = STATE(42),
    [sym__directive] = STATE(2),
    [sym_disable_directive] = STATE(2),
    [sym_enable_directive] = STATE(2),
    [sym_extended_analysis_directive] = STATE(2),
    [sym_external_sources_directive] = STATE(2),
    [sym_source_directive] = STATE(2),
    [sym_source_path_directive] = STATE(2),
    [sym_shell_directive] = STATE(2),
    [aux_sym_shellcheckrc_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_disable] = ACTIONS(7),
    [anon_sym_enable] = ACTIONS(9),
    [anon_sym_extended_DASHanalysis] = ACTIONS(11),
    [anon_sym_external_DASHsources] = ACTIONS(13),
    [anon_sym_source] = ACTIONS(15),
    [anon_sym_source_DASHpath] = ACTIONS(17),
    [anon_sym_shell] = ACTIONS(19),
    [sym_comment] = ACTIONS(3),
    [sym__whitespace] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(7), 1,
      anon_sym_disable,
    ACTIONS(9), 1,
      anon_sym_enable,
    ACTIONS(11), 1,
      anon_sym_extended_DASHanalysis,
    ACTIONS(13), 1,
      anon_sym_external_DASHsources,
    ACTIONS(15), 1,
      anon_sym_source,
    ACTIONS(17), 1,
      anon_sym_source_DASHpath,
    ACTIONS(19), 1,
      anon_sym_shell,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_comment,
      sym__whitespace,
    STATE(3), 9,
      sym__directive,
      sym_disable_directive,
      sym_enable_directive,
      sym_extended_analysis_directive,
      sym_external_sources_directive,
      sym_source_directive,
      sym_source_path_directive,
      sym_shell_directive,
      aux_sym_shellcheckrc_file_repeat1,
  [40] = 10,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    ACTIONS(25), 1,
      anon_sym_disable,
    ACTIONS(28), 1,
      anon_sym_enable,
    ACTIONS(31), 1,
      anon_sym_extended_DASHanalysis,
    ACTIONS(34), 1,
      anon_sym_external_DASHsources,
    ACTIONS(37), 1,
      anon_sym_source,
    ACTIONS(40), 1,
      anon_sym_source_DASHpath,
    ACTIONS(43), 1,
      anon_sym_shell,
    ACTIONS(3), 2,
      sym_comment,
      sym__whitespace,
    STATE(3), 9,
      sym__directive,
      sym_disable_directive,
      sym_enable_directive,
      sym_extended_analysis_directive,
      sym_external_sources_directive,
      sym_source_directive,
      sym_source_path_directive,
      sym_shell_directive,
      aux_sym_shellcheckrc_file_repeat1,
  [80] = 3,
    ACTIONS(48), 1,
      anon_sym_source,
    ACTIONS(3), 2,
      sym_comment,
      sym__whitespace,
    ACTIONS(46), 9,
      ts_builtin_sym_end,
      anon_sym_disable,
      anon_sym_enable,
      anon_sym_extended_DASHanalysis,
      anon_sym_external_DASHsources,
      anon_sym_source_DASHpath,
      anon_sym_shell,
      anon_sym_COMMA,
      anon_sym_DASH,
  [99] = 5,
    ACTIONS(52), 1,
      anon_sym_source,
    ACTIONS(54), 1,
      anon_sym_COMMA,
    STATE(8), 1,
      aux_sym__rule_id_list_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym__whitespace,
    ACTIONS(50), 7,
      ts_builtin_sym_end,
      anon_sym_disable,
      anon_sym_enable,
      anon_sym_extended_DASHanalysis,
      anon_sym_external_DASHsources,
      anon_sym_source_DASHpath,
      anon_sym_shell,
  [122] = 4,
    ACTIONS(58), 1,
      anon_sym_source,
    ACTIONS(60), 1,
      anon_sym_DASH,
    ACTIONS(3), 2,
      sym_comment,
      sym__whitespace,
    ACTIONS(56), 8,
      ts_builtin_sym_end,
      anon_sym_disable,
      anon_sym_enable,
      anon_sym_extended_DASHanalysis,
      anon_sym_external_DASHsources,
      anon_sym_source_DASHpath,
      anon_sym_shell,
      anon_sym_COMMA,
  [143] = 3,
    ACTIONS(64), 1,
      anon_sym_source,
    ACTIONS(3), 2,
      sym_comment,
      sym__whitespace,
    ACTIONS(62), 9,
      ts_builtin_sym_end,
      anon_sym_disable,
      anon_sym_enable,
      anon_sym_extended_DASHanalysis,
      anon_sym_external_DASHsources,
      anon_sym_source_DASHpath,
      anon_sym_shell,
      anon_sym_COMMA,
      anon_sym_DASH,
  [162] = 5,
    ACTIONS(54), 1,
      anon_sym_COMMA,
    ACTIONS(68), 1,
      anon_sym_source,
    STATE(9), 1,
      aux_sym__rule_id_list_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym__whitespace,
    ACTIONS(66), 7,
      ts_builtin_sym_end,
      anon_sym_disable,
      anon_sym_enable,
      anon_sym_extended_DASHanalysis,
      anon_sym_external_DASHsources,
      anon_sym_source_DASHpath,
      anon_sym_shell,
  [185] = 5,
    ACTIONS(72), 1,
      anon_sym_source,
    ACTIONS(74), 1,
      anon_sym_COMMA,
    STATE(9), 1,
      aux_sym__rule_id_list_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym__whitespace,
    ACTIONS(70), 7,
      ts_builtin_sym_end,
      anon_sym_disable,
      anon_sym_enable,
      anon_sym_extended_DASHanalysis,
      anon_sym_external_DASHsources,
      anon_sym_source_DASHpath,
      anon_sym_shell,
  [208] = 3,
    ACTIONS(72), 1,
      anon_sym_source,
    ACTIONS(3), 2,
      sym_comment,
      sym__whitespace,
    ACTIONS(70), 8,
      ts_builtin_sym_end,
      anon_sym_disable,
      anon_sym_enable,
      anon_sym_extended_DASHanalysis,
      anon_sym_external_DASHsources,
      anon_sym_source_DASHpath,
      anon_sym_shell,
      anon_sym_COMMA,
  [226] = 3,
    ACTIONS(79), 1,
      anon_sym_source,
    ACTIONS(3), 2,
      sym_comment,
      sym__whitespace,
    ACTIONS(77), 8,
      ts_builtin_sym_end,
      anon_sym_disable,
      anon_sym_enable,
      anon_sym_extended_DASHanalysis,
      anon_sym_external_DASHsources,
      anon_sym_source_DASHpath,
      anon_sym_shell,
      anon_sym_COMMA,
  [244] = 3,
    ACTIONS(83), 1,
      anon_sym_source,
    ACTIONS(3), 2,
      sym_comment,
      sym__whitespace,
    ACTIONS(81), 7,
      ts_builtin_sym_end,
      anon_sym_disable,
      anon_sym_enable,
      anon_sym_extended_DASHanalysis,
      anon_sym_external_DASHsources,
      anon_sym_source_DASHpath,
      anon_sym_shell,
  [261] = 7,
    ACTIONS(85), 1,
      sym_all,
    ACTIONS(87), 1,
      anon_sym_SC,
    ACTIONS(89), 1,
      sym_integer,
    STATE(6), 1,
      sym_rule_id,
    ACTIONS(3), 2,
      sym_comment,
      sym__whitespace,
    STATE(5), 2,
      sym__rule_id,
      sym_rule_id_range,
    STATE(12), 2,
      sym__disable_value,
      sym__rule_id_list,
  [286] = 3,
    ACTIONS(93), 1,
      anon_sym_source,
    ACTIONS(3), 2,
      sym_comment,
      sym__whitespace,
    ACTIONS(91), 7,
      ts_builtin_sym_end,
      anon_sym_disable,
      anon_sym_enable,
      anon_sym_extended_DASHanalysis,
      anon_sym_external_DASHsources,
      anon_sym_source_DASHpath,
      anon_sym_shell,
  [303] = 3,
    ACTIONS(97), 1,
      anon_sym_source,
    ACTIONS(3), 2,
      sym_comment,
      sym__whitespace,
    ACTIONS(95), 7,
      ts_builtin_sym_end,
      anon_sym_disable,
      anon_sym_enable,
      anon_sym_extended_DASHanalysis,
      anon_sym_external_DASHsources,
      anon_sym_source_DASHpath,
      anon_sym_shell,
  [320] = 3,
    ACTIONS(101), 1,
      anon_sym_source,
    ACTIONS(3), 2,
      sym_comment,
      sym__whitespace,
    ACTIONS(99), 7,
      ts_builtin_sym_end,
      anon_sym_disable,
      anon_sym_enable,
      anon_sym_extended_DASHanalysis,
      anon_sym_external_DASHsources,
      anon_sym_source_DASHpath,
      anon_sym_shell,
  [337] = 3,
    ACTIONS(105), 1,
      anon_sym_source,
    ACTIONS(3), 2,
      sym_comment,
      sym__whitespace,
    ACTIONS(103), 7,
      ts_builtin_sym_end,
      anon_sym_disable,
      anon_sym_enable,
      anon_sym_extended_DASHanalysis,
      anon_sym_external_DASHsources,
      anon_sym_source_DASHpath,
      anon_sym_shell,
  [354] = 3,
    ACTIONS(109), 1,
      anon_sym_source,
    ACTIONS(3), 2,
      sym_comment,
      sym__whitespace,
    ACTIONS(107), 7,
      ts_builtin_sym_end,
      anon_sym_disable,
      anon_sym_enable,
      anon_sym_extended_DASHanalysis,
      anon_sym_external_DASHsources,
      anon_sym_source_DASHpath,
      anon_sym_shell,
  [371] = 3,
    ACTIONS(113), 1,
      anon_sym_source,
    ACTIONS(3), 2,
      sym_comment,
      sym__whitespace,
    ACTIONS(111), 7,
      ts_builtin_sym_end,
      anon_sym_disable,
      anon_sym_enable,
      anon_sym_extended_DASHanalysis,
      anon_sym_external_DASHsources,
      anon_sym_source_DASHpath,
      anon_sym_shell,
  [388] = 3,
    ACTIONS(117), 1,
      anon_sym_source,
    ACTIONS(3), 2,
      sym_comment,
      sym__whitespace,
    ACTIONS(115), 7,
      ts_builtin_sym_end,
      anon_sym_disable,
      anon_sym_enable,
      anon_sym_extended_DASHanalysis,
      anon_sym_external_DASHsources,
      anon_sym_source_DASHpath,
      anon_sym_shell,
  [405] = 3,
    ACTIONS(121), 1,
      anon_sym_source,
    ACTIONS(3), 2,
      sym_comment,
      sym__whitespace,
    ACTIONS(119), 7,
      ts_builtin_sym_end,
      anon_sym_disable,
      anon_sym_enable,
      anon_sym_extended_DASHanalysis,
      anon_sym_external_DASHsources,
      anon_sym_source_DASHpath,
      anon_sym_shell,
  [422] = 3,
    ACTIONS(125), 1,
      anon_sym_source,
    ACTIONS(3), 2,
      sym_comment,
      sym__whitespace,
    ACTIONS(123), 7,
      ts_builtin_sym_end,
      anon_sym_disable,
      anon_sym_enable,
      anon_sym_extended_DASHanalysis,
      anon_sym_external_DASHsources,
      anon_sym_source_DASHpath,
      anon_sym_shell,
  [439] = 3,
    ACTIONS(129), 1,
      anon_sym_source,
    ACTIONS(3), 2,
      sym_comment,
      sym__whitespace,
    ACTIONS(127), 7,
      ts_builtin_sym_end,
      anon_sym_disable,
      anon_sym_enable,
      anon_sym_extended_DASHanalysis,
      anon_sym_external_DASHsources,
      anon_sym_source_DASHpath,
      anon_sym_shell,
  [456] = 3,
    STATE(20), 1,
      sym_shell,
    ACTIONS(3), 2,
      sym_comment,
      sym__whitespace,
    ACTIONS(131), 5,
      anon_sym_sh,
      anon_sym_bash,
      anon_sym_dash,
      anon_sym_ksh,
      anon_sym_busybox,
  [471] = 5,
    ACTIONS(133), 1,
      anon_sym_SQUOTE,
    ACTIONS(135), 1,
      anon_sym_DQUOTE,
    ACTIONS(137), 1,
      aux_sym_identifier_token1,
    ACTIONS(3), 2,
      sym_comment,
      sym__whitespace,
    STATE(17), 3,
      sym__source_value,
      sym_string,
      sym_identifier,
  [490] = 5,
    ACTIONS(133), 1,
      anon_sym_SQUOTE,
    ACTIONS(135), 1,
      anon_sym_DQUOTE,
    ACTIONS(137), 1,
      aux_sym_identifier_token1,
    ACTIONS(3), 2,
      sym_comment,
      sym__whitespace,
    STATE(23), 3,
      sym__source_value,
      sym_string,
      sym_identifier,
  [509] = 5,
    ACTIONS(87), 1,
      anon_sym_SC,
    ACTIONS(89), 1,
      sym_integer,
    STATE(6), 1,
      sym_rule_id,
    ACTIONS(3), 2,
      sym_comment,
      sym__whitespace,
    STATE(10), 2,
      sym__rule_id,
      sym_rule_id_range,
  [527] = 4,
    ACTIONS(139), 1,
      sym_all,
    ACTIONS(141), 1,
      aux_sym_identifier_token1,
    STATE(15), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_comment,
      sym__whitespace,
  [541] = 3,
    STATE(18), 1,
      sym_boolean,
    ACTIONS(3), 2,
      sym_comment,
      sym__whitespace,
    ACTIONS(143), 2,
      anon_sym_true,
      anon_sym_false,
  [553] = 3,
    STATE(16), 1,
      sym_boolean,
    ACTIONS(3), 2,
      sym_comment,
      sym__whitespace,
    ACTIONS(143), 2,
      anon_sym_true,
      anon_sym_false,
  [565] = 4,
    ACTIONS(87), 1,
      anon_sym_SC,
    ACTIONS(89), 1,
      sym_integer,
    STATE(11), 1,
      sym_rule_id,
    ACTIONS(3), 2,
      sym_comment,
      sym__whitespace,
  [579] = 2,
    ACTIONS(145), 1,
      anon_sym_DQUOTE,
    ACTIONS(3), 2,
      sym_comment,
      sym__whitespace,
  [587] = 2,
    ACTIONS(147), 1,
      anon_sym_EQ,
    ACTIONS(3), 2,
      sym_comment,
      sym__whitespace,
  [595] = 2,
    ACTIONS(149), 1,
      anon_sym_EQ,
    ACTIONS(3), 2,
      sym_comment,
      sym__whitespace,
  [603] = 2,
    ACTIONS(151), 1,
      anon_sym_EQ,
    ACTIONS(3), 2,
      sym_comment,
      sym__whitespace,
  [611] = 2,
    ACTIONS(153), 1,
      anon_sym_EQ,
    ACTIONS(3), 2,
      sym_comment,
      sym__whitespace,
  [619] = 2,
    ACTIONS(155), 1,
      anon_sym_EQ,
    ACTIONS(3), 2,
      sym_comment,
      sym__whitespace,
  [627] = 2,
    ACTIONS(157), 1,
      aux_sym_string_token1,
    ACTIONS(159), 2,
      sym_comment,
      sym__whitespace,
  [635] = 2,
    ACTIONS(145), 1,
      anon_sym_SQUOTE,
    ACTIONS(3), 2,
      sym_comment,
      sym__whitespace,
  [643] = 2,
    ACTIONS(161), 1,
      anon_sym_EQ,
    ACTIONS(3), 2,
      sym_comment,
      sym__whitespace,
  [651] = 2,
    ACTIONS(163), 1,
      aux_sym_string_token2,
    ACTIONS(159), 2,
      sym_comment,
      sym__whitespace,
  [659] = 2,
    ACTIONS(165), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_comment,
      sym__whitespace,
  [667] = 2,
    ACTIONS(167), 1,
      anon_sym_EQ,
    ACTIONS(3), 2,
      sym_comment,
      sym__whitespace,
  [675] = 2,
    ACTIONS(169), 1,
      sym_integer,
    ACTIONS(3), 2,
      sym_comment,
      sym__whitespace,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 40,
  [SMALL_STATE(4)] = 80,
  [SMALL_STATE(5)] = 99,
  [SMALL_STATE(6)] = 122,
  [SMALL_STATE(7)] = 143,
  [SMALL_STATE(8)] = 162,
  [SMALL_STATE(9)] = 185,
  [SMALL_STATE(10)] = 208,
  [SMALL_STATE(11)] = 226,
  [SMALL_STATE(12)] = 244,
  [SMALL_STATE(13)] = 261,
  [SMALL_STATE(14)] = 286,
  [SMALL_STATE(15)] = 303,
  [SMALL_STATE(16)] = 320,
  [SMALL_STATE(17)] = 337,
  [SMALL_STATE(18)] = 354,
  [SMALL_STATE(19)] = 371,
  [SMALL_STATE(20)] = 388,
  [SMALL_STATE(21)] = 405,
  [SMALL_STATE(22)] = 422,
  [SMALL_STATE(23)] = 439,
  [SMALL_STATE(24)] = 456,
  [SMALL_STATE(25)] = 471,
  [SMALL_STATE(26)] = 490,
  [SMALL_STATE(27)] = 509,
  [SMALL_STATE(28)] = 527,
  [SMALL_STATE(29)] = 541,
  [SMALL_STATE(30)] = 553,
  [SMALL_STATE(31)] = 565,
  [SMALL_STATE(32)] = 579,
  [SMALL_STATE(33)] = 587,
  [SMALL_STATE(34)] = 595,
  [SMALL_STATE(35)] = 603,
  [SMALL_STATE(36)] = 611,
  [SMALL_STATE(37)] = 619,
  [SMALL_STATE(38)] = 627,
  [SMALL_STATE(39)] = 635,
  [SMALL_STATE(40)] = 643,
  [SMALL_STATE(41)] = 651,
  [SMALL_STATE(42)] = 659,
  [SMALL_STATE(43)] = 667,
  [SMALL_STATE(44)] = 675,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_shellcheckrc_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_shellcheckrc_file, 1, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_shellcheckrc_file_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_shellcheckrc_file_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_shellcheckrc_file_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_shellcheckrc_file_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_shellcheckrc_file_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_shellcheckrc_file_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_shellcheckrc_file_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_shellcheckrc_file_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule_id, 2, 0, 2),
  [48] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_rule_id, 2, 0, 2),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__rule_id_list, 1, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__rule_id_list, 1, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__rule_id, 1, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__rule_id, 1, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule_id, 1, 0, 1),
  [64] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_rule_id, 1, 0, 1),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__rule_id_list, 2, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__rule_id_list, 2, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__rule_id_list_repeat1, 2, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__rule_id_list_repeat1, 2, 0, 0),
  [74] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__rule_id_list_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule_id_range, 3, 0, 3),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_rule_id_range, 3, 0, 3),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_disable_directive, 3, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_disable_directive, 3, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enable_directive, 3, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_enable_directive, 3, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_external_sources_directive, 3, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_external_sources_directive, 3, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_directive, 3, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_source_directive, 3, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extended_analysis_directive, 3, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_extended_analysis_directive, 3, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_shell, 1, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_shell, 1, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_shell_directive, 3, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_shell_directive, 3, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_identifier, 1, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_path_directive, 3, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_source_path_directive, 3, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [141] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [157] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [159] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [163] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [165] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_shellcheckrc(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "shellcheckrc",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
